### ISSUE TITLE
Some operations should not require authentication

### ISSUE THREAD

**Issue by mcowger** [OneDrive/onedrive-sdk-python#1]
For example, I have a couple shared OneDrive folders that are available totally anonymously through the web interface (example: http://1drv.ms/1FWwXAk) that i'd love to access via this SDK....but if I have to authenticate thats a problem....

Thoughts?

**Comment by rgregg** [comment]
Our API doesn't provide this functionality yet, but it's on our radar. When the API has this support, the SDK will be updated to support it as well.
