### ISSUE TITLE
How to get createdDateTime for a file using id#

### ISSUE THREAD

**Issue by app5000** [OneDrive/onedrive-sdk-python#100]
I tried to get the created timestamp for a file in one drive using client.item(id=itemid).get().createdDateTime but got an error msg:
AttributeError: 'Item' object has no attribute 'createdDateTime'.

when I tried client.item(id=fileid).get(), I got <onedrivesdk.model.item.Item object at 0x11b412ed0>.  What does this mean?

I found references to the 'createdDateTime' attribute in drive item object.  I can not make this error go away.  Where can I find this time stamp? which object within the onedrive api has this attribute?

Thanks for any help.

**Comment by schvarcz** [comment]
Hello.

In the python api they use the python style. You can get the created DateTime by:

```python 
item = client.item(id=item_id).get()
print item.created_date_time
```

However, for syncing purposes, I think it would be better to use:

```python 
item = client.item(id=item_id).get()
print item.last_modified_date_time, item.last_modified_by.user.display_name
```

Kind regards.

**Comment by app5000** [comment]
Thank you for your help.  I was able to fixed the problem with an answer from onedrive-api-docs.  Your answer works too.  Here is the link to the other answer  https://github.com/OneDrive/onedrive-api-docs/issues/551#issuecomment-287216061.

Thanks for getting back to me.

Regards,.
