### ISSUE TITLE
Creating a Onedrive client from access_token with code flow

### ISSUE THREAD

**Issue by susamn** [OneDrive/onedrive-sdk-python#101]
I am using https://login.live.com/oauth20_authorize.srf to get access_token and refresh_token and managing the refresh myself. How can I use the access_token to create a client from the sdk and use Graph to connect to Onedrive? Is there a way? I don't want to use REST api, I want to rely on the sdk, as any change in the REST api will be managed by the sdk.

Referring to the documentation ; 
https://dev.onedrive.com/auth/graph_oauth.htm

I cannot find a suitable example to use python sdk to be used in code flow

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
