### ISSUE TITLE
upload_async fails with large files

### ISSUE THREAD

**Issue by oleo65** [OneDrive/onedrive-sdk-python#103]
I was using the proposed solution in #51 for uploading large files (> 100MB).

The `upload_async` method is working well for files which do not require chunking and therefore don't require an upload session. However when trying to upload a file which requires an upload session an `OneDriveError` is raised with `invalidRequest - API not found`.

The line which triggered the upload was:
`client.item(drive='me', id='ID').children['testfile.bin'].upload_async('largeLocalFile.bin')`

This issue might possibly be related to API changes (namespace changes) mentioned [here](http://stackoverflow.com/questions/42458796/onedrive-api-createuploadsession-api-not-found). Are there any plans to adapt the current python code to the changed API specifications?

**Comment by edgaru** [comment]
I have the same issue. Any solution?

**Comment by oleo65** [comment]
This issue might possibly related to #104 

Additional information: Checked with Python version 3.4.2 and 3.6.0. Both not working and raising the same error described above.

**Comment by papou-github** [comment]
I also tried with 3.6.3 on Ubuntu 16.04 and still have : API not Found
Do you have any update or workaround as from my point of view without clear solution this API is unusable as you cannot upload "large" file ... ?
Python 3.6.3 (default, Oct  6 2017, 08:44:35)
Thank you !

Traceback (most recent call last):
  File "./TEST.py", line 214, in upload_file
    returned_item = CLIENT.item(drive="me", id=full_path).children[file_name].upload_async(source_file)
  File "/usr/local/lib/python3.6/dist-packages/onedrivesdk/version_bridge/fragment_upload.py", line 160, in fragment_upload_async
    session = self.create_session(item).post()
  File "/usr/local/lib/python3.6/dist-packages/onedrivesdk/request/item_create_session.py", line 106, in post
    return self.request().post()
  File "/usr/local/lib/python3.6/dist-packages/onedrivesdk/request/item_create_session.py", line 60, in post
    entity = UploadSession(json.loads(self.send(self.body_options).content))
  File "/usr/local/lib/python3.6/dist-packages/onedrivesdk/request_base.py", line 163, in send
    content=content_dict)
  File "/usr/local/lib/python3.6/dist-packages/onedrivesdk/http_provider.py", line 71, in send
    custom_response = HttpResponse(response.status_code, response.headers, response.text)
  File "/usr/local/lib/python3.6/dist-packages/onedrivesdk/http_response.py", line 59, in __init__
    raise OneDriveError(message["error"], self.status)
onedrivesdk.error.OneDriveError: invalidRequest - API not found

**Comment by KTibow** [comment]
@papou-github @edgaru @oleo65 I don't have this issue when uploading 4.62 GB files. Try upgrading onedrive-sdk and regenerating your client_id and client_secret.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
