### ISSUE TITLE
upload_async doesn't upload files asynchronous in python>=3.4

### ISSUE THREAD

**Issue by AlexNigl** [OneDrive/onedrive-sdk-python#104]
[onedrivesdk/version_bridge/fragment_upload.py](https://github.com/OneDrive/onedrive-sdk-python/blob/master/src/onedrivesdk/version_bridge/fragment_upload.py) overwrites the default method [`upload_async`](https://github.com/OneDrive/onedrive-sdk-python/blob/e5642f8cad8eea37a4f653c1a23dfcfc06c37110/src/python3/request/item_request_builder.py#L119-L120) without being a coroutine itself or using asynchronous post functions.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
