### ISSUE TITLE
invalid_grant if request readonly instead of readwrite

### ISSUE THREAD

**Issue by garretfick** [OneDrive/onedrive-sdk-python#107]
Hi,

I followed the authentication instructions as described in the readme. However, I changed the requested permissions to request `onedrive.readonly` instead of `onedrive.readwrite` since I only need to read files (see [https://dev.onedrive.com/auth/msa_oauth.htm]).

However, when I request `readonly` permissions, I get the exception: `Exception: invalid_grant`.

**Comment by Sam-khorsand** [comment]
For me, it gives the same error also with files.readwrite.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
