### ISSUE TITLE
How to get quota

### ISSUE THREAD

**Issue by nakioman** [OneDrive/onedrive-sdk-python#108]
Can someone point me to an example on how to get the quota with the Api?
Thanks

**Comment by cnbeining** [comment]
https://github.com/cnbeining/onedrivecmd/blob/master/onedrivecmd/utils/actions.py#L512-L546

**Comment by KTibow** [comment]
@nakioman does that solve your issue? Consider closing. If you think it should be part of the OneDrive SDK, keep in mind it's supposed to be a simple SDK.

**Comment by nakioman** [comment]
Yes, thanks
