### ISSUE TITLE
How does this relate to the msgraph pypi package?

### ISSUE THREAD

**Issue by rkhwaja** [OneDrive/onedrive-sdk-python#111]
Please add something to the readme regarding this. Both this package and the msgraph package claim to be the official way to access OneDrive.

The readme should explain which one is appropriate for which situation.

**Comment by KTibow** [comment]
@rkhwaja I'm updating the docs. Can you outline how it goes? (I can't copy your work due to the CLA.)

**Comment by rkhwaja** [comment]
I don't know - I was asking someone from Microsoft to clear it up for me. I'm not using this library anymore - I thought it stopped working.

**Comment by KTibow** [comment]
@rkhwaja The library does still work. The previous [python-onedrive](https://github.com/mk-fg/python-onedrive) redirects to this. What's the link to the python msgraph package?

**Comment by KTibow** [comment]
The msgraph package is a fork. Usually the main repo is the father of the fork.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
