### ISSUE TITLE
Unicode issue in paths

### ISSUE THREAD

**Issue by dfeinzeig** [OneDrive/onedrive-sdk-python#115]
If the path passed to

https://github.com/OneDrive/onedrive-sdk-python/blob/master/src/onedrivesdk/extensions/drive_request_builder_helper.py#L40

contains a unicode character it blows up with a unicode error. Is it valid to have unicode characters in paths in onedrive? if so, this should be updated.

**Comment by rudr4x5h** [comment]
This PR(#137) may address and provide a quick fix for this issue considering unicode character is not allowed in paths.

**Comment by KTibow** [comment]
@DataSapient I recommend you have this behavior implemented in your PR:
1. Include it in the docs
2. By default remove unicode characters
3. Raise a warning when it removes unicode characters, by default
4. Have an option on whether to remove unicode or not
5. If they manually say they want to remove unicode not raise a warning
That should keep everyone happy.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
