### ISSUE TITLE
How to get access_token and reuse it to make api call using python sdk

### ISSUE THREAD

**Issue by app5000** [OneDrive/onedrive-sdk-python#117]
Hello,

Can one get access_token if using python sdk authentication?  I am following the instruction on this page: https://github.com/OneDrive/onedrive-sdk-python.  However, I see no mention of access_token and don't how to get it and reuse it to make api calls.  Can anyone help?

Idealy, I want to save token into session['onedrive']=access_token.  If this is doable, how do I use access_token to reconstruct client?

**Comment by easy4dtam** [comment]
I was able to make it work.   Basically, I use the example code to setup most of the call, but using selenium to access the URL and go thru the login pages to pick up the code from the response URL.  Once acquired the code you can authenticate and save the session using a pickle file.  Load the pickle file for your subsequent access.  These are the old urls I used:
        self.discovery_uri = 'https://api.office.com/discovery/'
        self.auth_server_url='https://login.microsoftonline.com/common/oauth2/authorize'
        self.auth_token_url='https://login.microsoftonline.com/common/oauth2/token'

**Comment by app5000** [comment]
I ended uo saving it in session.  if you save it in a pickled file, what happens when it is expired?
    On Monday, December 11, 2017, 7:39:52 PM EST, easy4dtam <notifications@github.com> wrote:  
 
 
I was able to make it work. Basically, I use the example code to setup most of the call, but using selenium to access the URL and go thru the login pages to pick up the code from the response URL. Once acquired the code you can authenticate and save the session using a pickle file. Load the pickle file for your subsequent access. These are the old urls I used:
self.discovery_uri = 'https://api.office.com/discovery/'
self.auth_server_url='https://login.microsoftonline.com/common/oauth2/authorize'
self.auth_token_url='https://login.microsoftonline.com/common/oauth2/token'

**Comment by easy4dtam** [comment]
it is the same thing for me.  the pickle file is the file for my saved session.

**Comment by app5000** [comment]
The only problem I have now is not knowing when I have to re-authenticate again.  I don't know how to auto-redirect to my authentication function when the error message comes up.  Did you set it up to auto-reauthenticate when the token expires?
    On Wednesday, December 13, 2017, 5:49:50 PM EST, easy4dtam <notifications@github.com> wrote:  
 
 
it is the same thing for me. the pickle file is the file for my saved session.

**Comment by KTibow** [comment]
@app5000 and @easy4dtam this is how I do it:
```python3
import onedrivesdk, os, asyncio
from onedrivesdk.helpers import GetAuthCodeServer

scopes=['wl.signin', 'wl.offline_access', 'onedrive.readwrite']
http_provider = onedrivesdk.HttpProvider()
client_id='my_client_id_you_cant_see'
base_url='https://api.onedrive.com/v1.0/'
auth_provider = onedrivesdk.AuthProvider(http_provider,
                                         client_id,
                                         scopes)
auth_provider.load_session()
auth_provider.refresh_token()
client = onedrivesdk.OneDriveClient(base_url, auth_provider, http_provider)
# stuff here
auth_provider.save_session()
```
This automatically refreshes the token.
If this solves your problem consider closing.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
