### ISSUE TITLE
https://api.office.com/discovery/ raises 404

### ISSUE THREAD

**Issue by jjorissen52** [OneDrive/onedrive-sdk-python#118]
https://api.office.com/discovery/v2.0/me does not. But it does return an invalid resource (allServices). Not sure where to go from here.

**Comment by KTibow** [comment]
@jjorissen52 upgrade your library with
```
pip3 install git+https://github.com/OneDrive/onedrive-sdk-python.git
pip3 install --upgrade git+https://github.com/OneDrive/onedrive-sdk-python.git
```
and try running again.
If that works, consider closing.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
