### ISSUE TITLE
How to share a folder/file with an user/email?

### ISSUE THREAD

**Issue by easy4dtam** [OneDrive/onedrive-sdk-python#120]
Hi all,
      Anyone tried to share a folder/file with another user using this SDK?  I know the model has permissions object available, I just need a small example of tying item() with permission() with share attributes to make it work if it is indeed supported..  Thanks very much in advanced.

**Comment by KTibow** [comment]
@easy4dtam there is a `create_link()` attribute. You can try finding a Outlook SDK.

**Comment by KTibow** [comment]
@easy4dtam here's the sharing docs: https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_invite?view=odsp-graph-online

**Comment by KTibow** [comment]
Use the `item.invite()` method.
Consider closing.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
