### ISSUE TITLE
Request: How do I read the data from an office 365 excel spreadsheet without having to download the entire document?

### ISSUE THREAD

**Issue by terrainthesky1** [OneDrive/onedrive-sdk-python#121]
I haven't been able to find out how to do it anywhere.

**Comment by KTibow** [comment]
@terrainthesky1 You'd need to try to find a Excel Online API/SDK, or run a script in the cloud that downloads it and parses it. The OneDrive SDK is a simple SDK for working with everything OneDrive, not everything Office. Consider closing.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
