### ISSUE TITLE
Use Device Code oauth flow for a much better experience

### ISSUE THREAD

**Issue by dbsanfte** [OneDrive/onedrive-sdk-python#123]
https://hk.saowen.com/a/c476afb9db3b6f9d6809d4008b0dca5f54533392e713ed5ed4deb3a674b63b72

This provides a much better user experience than copy/pasting the code= stuff in the address bar.

**Comment by KTibow** [comment]
@dbsanfte your link currently redirects to [dogedoge](https://www.dogedoge.com/), so I don't know what you're talking about. We can spin up a server though so we don't have to deal with copy/pasting with this:
```python3
import onedrivesdk
from onedrivesdk.helpers import GetAuthCodeServer

redirect_uri = 'http://localhost:8080/'
client_secret = 'your_app_secret'
scopes=['wl.signin', 'wl.offline_access', 'onedrive.readwrite']

client = onedrivesdk.get_default_client(
    client_id='your_client_id', scopes=scopes)

auth_url = client.auth_provider.get_auth_url(redirect_uri)

#this will block until we have the code
code = GetAuthCodeServer.get_auth_code(auth_url, redirect_uri)

client.auth_provider.authenticate(code, redirect_uri, client_secret)
```
If that helped consider closing.
