### ISSUE TITLE
Invalid JSON when uploading CSV

### ISSUE THREAD

**Issue by rschork** [OneDrive/onedrive-sdk-python#125]
I have been getting this error a lot recently -- mainly when uploading larger csvs (80mb or so).

'''
onedrivesdk.error.OneDriveError: malformed - The following invalid JSON was returned: <!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'><html xmlns='http://www.w3.org/1999/xhtml'><head><meta content='text/html; charset=utf-8' http-equiv='content-type'/><style type='text/css'>body {font-family:Arial; margin-left:40px; }img  {border:0 none; }#content { margin-left: auto; margin-right: auto }#message h2 { font-size: 20px; font-weight: normal; color: #000000; margin: 34px 0px 0px 0px }#message p  { font-size: 13px; color: #000000; margin: 7px 0px 0px0px}#errorref { font-size: 11px; color: #737373; margin-top: 41px }</style><title>OneDrive</title></head><body><div id='content'><div id='message'>Our services aren't available right now We're working to restore all services as soon as possible. Please check back soon.</div><div id='errorref'><span>Ref A: 106DA54BC29E4340B334EDE899669B52 Ref B: AMS04EDGE0417 Ref C: 2018-04-30T19:57:06Z</span></div></div></body></html>'''

**Comment by KTibow** [comment]
@rschork Try again, because 2 years is a lot longer than soon, and maybe try `upload_async()` instead. If that helps, consider closing.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
