### ISSUE TITLE
cannot get item changes

### ISSUE THREAD

**Issue by dfeinzeig** [OneDrive/onedrive-sdk-python#126]
When trying to get item changes, seeing this response:

`{"error":{"code":"invalidRequest, "message":"You cannot get the content of the current version"}}`

We have not changed anything, and this was working yesterday. Thoughts?

**Comment by KTibow** [comment]
@dfeinzeig it's saying you're trying to get the content of the current version. It's saying you if you want to find the content of the current version, you should use `item.download()`. Try changing which version you're trying to download.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
