### ISSUE TITLE
OneDrive for business authentication without user

### ISSUE THREAD

**Issue by sathaley1** [OneDrive/onedrive-sdk-python#127]
I am looking for authenticating my app wihouth the need of a browser to provide consent. Admin consent has already been granted to the app via Azure portal. I am looking for the same functionality as provided via:
https://developer.microsoft.com/en-us/graph/docs/concepts/auth_v2_service

**Comment by KTibow** [comment]
@sathaley1 do you think that anybody else wants the same thing? Are you still working on this? Given that onedrive-sdk-python is supposed to be simple, if not, consider closing.

An alternative way is to use the `save_session()` function once. The next time, I call `load_session()`, `refresh_token()`, and when I'm done `save_session()` again. It saves it to a `session.pickle` file which I just move along to be in the same directory as the program.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
