### ISSUE TITLE
Does this SDK still up to date?

### ISSUE THREAD

**Issue by tigercosmos** [OneDrive/onedrive-sdk-python#129]
It seems the SDK has stopped to update for two years. Does this SDK support the latest graph API?

**Comment by ecebuzz** [comment]
I don't think so.

**Comment by tscholze** [comment]
Neither do I. But what's the replacement? Graph API does not work for OneDrive Personal.

Did you find another SDK which works? @tigercosmos, @ecebuzz?

**Comment by tigercosmos** [comment]
I thought it still works, but it is just not maintained anymore.

**Comment by earonesty** [comment]
It's not maintained.   We are trying to get a fork up-to-speed, but may give up and use the REST api directly unless there's significant interest.

**Comment by KTibow** [comment]
@tigercosmos It seems to work for me in 2020 without any deprecation notices.
I'm trying to get the top 3 contributors attention by @mentioning them in my [pull request](https://github.com/OneDrive/onedrive-sdk-python/pull/174) and my [issue](https://github.com/OneDrive/onedrive-sdk-python/issues/175).

Just so you know, the [onedrivesdk-fork is complete](https://pypi.org/project/onedrivesdk-fork/), and this issue isn't in the top page of issues anymore.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
