### ISSUE TITLE
CLI tool

### ISSUE THREAD

**Issue by szepeviktor** [OneDrive/onedrive-sdk-python#13]
Do you plan to provide a CLI tool that implement all/most SDK features?

**Comment by cdmayer** [comment]
You're in luck! If you take a look at [the examples directory](https://github.com/OneDrive/onedrive-sdk-python/tree/master/examples) you can see that we have already partially implemented such a tool as an example in how to use the SDK. If it's missing any features you would expect, feel free to submit a PR!

**Comment by szepeviktor** [comment]
Thank you.
