### ISSUE TITLE
Error for connect to ONE DRIVE

### ISSUE THREAD

**Issue by DenisEvgrafov** [OneDrive/onedrive-sdk-python#133]
Hello! Can you help me? I have a problem with connect to one drive account. I use next programming code:
`redirect_uri = 'http://localhost:8080/'
client_secret = '******'
scopes=['wl.signin', 'wl.offline_access', 'onedrive.readwrite']
client = onedrivesdk.get_default_client(
client_id='*****', scopes=scopes)
auth_url = client.auth_provider.get_auth_url(redirect_uri)
#this will block until we have the code
code = GetAuthCodeServer.get_auth_code(auth_url, redirect_uri)
#code = 'M6ab12796-77c7-e4b3-f8b6-9b655e3ccc60'
client.auth_provider.authenticate(code, redirect_uri, client_secret)`
client_secret and client_id equal value from my account. But what is the value i must set in "redirect_uri'? I'm not using web-server and address "localhost:8080" unavailible. 
My task is the BackUp file and upload in the OneDrive Account. Okey, can i execute query without "redirect_uri"? How can replace? 
Thank you!

**Comment by comnutssg** [comment]
So I was just starting to play with this sdk as well, found that I need to add a Web platform and the uri in My Applications portal.

![image](https://user-images.githubusercontent.com/34881018/43937306-73e76236-9c8f-11e8-9e57-fdcf485556d5.png)

**Comment by comnutssg** [comment]
You also might want to change the code from onedrivesdk.get_default_client to onedrivesdk.get_consumer_client.

According to the source, [get_default_client is deprecated](../commit/80eee9fbe6e3ff99ab15ac1491097c08a15244b5#diff-75689f2458cd71c487a6ce913b8badf2).

**Comment by DenisEvgrafov** [comment]
Thank you! I am not the Web-developer. It would be better for me to execute all process in console application, without user. Is it possible?

**Comment by comnutssg** [comment]
Nope, I was looking for that too. You will need authorization from the user in any case. I'm looking into network drive mapping instead now -- https://www.laptopmag.com/articles/map-onedrive-network-drive.

**Comment by KTibow** [comment]
@DenisEvgrafov you can use the other authentication method:
```python3
import onedrivesdk

redirect_uri = 'http://localhost:8080/'
client_secret = 'your_client_secret'
client_id='your_client_id'
api_base_url='https://api.onedrive.com/v1.0/'
scopes=['wl.signin', 'wl.offline_access', 'onedrive.readwrite']

http_provider = onedrivesdk.HttpProvider()
auth_provider = onedrivesdk.AuthProvider(
    http_provider=http_provider,
    client_id=client_id,
    scopes=scopes)

client = onedrivesdk.OneDriveClient(api_base_url, auth_provider, http_provider)
auth_url = client.auth_provider.get_auth_url(redirect_uri)
# Ask for the code
print('Paste this URL into your browser, approve the app\'s access.')
print('Copy everything in the address bar after "code=", and paste it below.')
print(auth_url)
code = input('Paste code here: ')

client.auth_provider.authenticate(code, redirect_uri, client_secret)
```
If this solved your issue consider closing.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
