### ISSUE TITLE
Shared File/Folder

### ISSUE THREAD

**Issue by vyacheslavparkhomenko** [OneDrive/onedrive-sdk-python#134]
Hello, please tell me how I could have access to a shared folder in onedrive with onedrive sdk?
Or I have next situation: I have a link to a file in one drive. How I could download this file with onedrivesdk python?
P.S. Very very very thanks everybody

**Comment by KTibow** [comment]
@vyacheslavparkhomenko here's the docs:
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/using-sharing-links?view=odsp-graph-online
You can do the alike as many others and use the requests library to do it. Given that the OneDrive SDK is supposed to be simple, if you don't think other people want that functionality, consider closing your issue.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
