### ISSUE TITLE
Authentication Issue 

### ISSUE THREAD

**Issue by ashu16815** [OneDrive/onedrive-sdk-python#139]
I am getting : 
{'error': {'code': '-2147024891, System.UnauthorizedAccessException', 'message': 'Access denied. You do not have permission to perform this action or access this resource.'}}  

Line error :     response = json.loads(requests.get(self._discovery_service_url, headers=headers).text)

What kind of permissions required ? How to assign that ? 

Thanks alot in advance for help.

**Comment by ashu16815** [comment]
`lass ResourceDiscoveryRequest(object):
    def __init__(self):
        self._method = 'GET'
        self._discovery_service_url = 'https://api.office.com/discovery/v2.0/me/services'

    def get_service_info(self, access_token):
        """Send request to discovery service. Return ServiceInfo
        for valid services.

        Args:
            access_token (str): A valid access token for resource
                'https://api.office.com/discovery/'

        Returns:
            List of :class:`ServiceInfo<onedrivesdk.helpers.resource_discovery.ServiceInfo>`:
                ServiceInfo for each service that the caller can access. NOTE: values that
                do not provide access to OneDrive for Business will be excluded (i.e. must have
                capability = 'MyFiles' and service_api_version = 'v2.0'
        """
        headers = {'Authorization': 'Bearer ' + access_token}
        print(requests)
        response = json.loads(requests.get(self._discovery_service_url, headers=headers).text)
        print(response)
        service_info_list = [ServiceInfo(x) for x in response['value']]
        trimmed_service_info_list = [si for si in service_info_list
                                     if si.capability == 'MyFiles' and si.service_api_version == 'v2.0']
        return trimmed_service_info_list`

Above is the code where I am getting below error: 

> {'error': {'code': '-2147024891, System.UnauthorizedAccessException', 'message': 'Access denied. You do not have permission to perform this action or access this resource.'}}

Guide to identify correct permissions required.

**Comment by segalion** [comment]
May be  same problem as posted here:
https://github.com/OneDrive/onedrive-sdk-python/issues/119#issuecomment-379048581
With new created accounts, service discover dont works. 

Usually, all people here are using accounts created before, that will work fine until nov-2019 

If yours is the same problem than this, you have to wait at least 1 year for someone to solve.

**Comment by KTibow** [comment]
@ashu16815 here's how to fix this:
1. Regenerate your `client_id` and `client_secret` at [Azure](https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationsListBlade).
2. Upgrade your library with
```
pip3 install git+https://github.com/OneDrive/onedrive-sdk-python.git
pip3 install --upgrade git+https://github.com/OneDrive/onedrive-sdk-python.git
```
If that solved your problem, consider closing. It's 2020 and it's working for me fine.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
