### ISSUE TITLE
We're unable to complete your request- authentication issue

### ISSUE THREAD

**Issue by tfitzhardinge** [OneDrive/onedrive-sdk-python#140]
Hi

I want to authenticate my onedrive drive personal account using python. Ultimately when I click into the auth URL the webpage does not generate a code.

When I execute the following code via a terminal in pycharm and clicked on the URL link it brings me to a MS webpage which states  

"We're unable to complete your request". And does not generate the code

I am coding the file in python 3.6 using pycharm. I have also tried the following code using python 3.7 and still get the same outcome.

I have gone through the application registration page generated the client_secret / password and obtained the client_id. I tried to choose web platform and a native desktop app as well and same outcome.

What step have I have missed.

The code that I am using is as follows. 

```
import onedreivesdk

redirect_uri = 'http://localhost:8080/'
client_secret = 'client_secret'
client_id='client_id'
api_base_url='https://api.onedrive.com/v1.0/'
scopes=['wl.signin', 'wl.offline_access', 'onedrive.readwrite']

http_provider = onedrivesdk.HttpProvider()
auth_provider = onedrivesdk.AuthProvider(
    http_provider=http_provider,
    client_id=client_id,
    scopes=scopes)

client = onedrivesdk.OneDriveClient(api_base_url, auth_provider, http_provider)
auth_url = client.auth_provider.get_auth_url(redirect_uri)
# Ask for the code
print('Paste this URL into your browser, approve the app\'s access.')
print('Copy everything in the address bar after "code=", and paste it below.')
print(auth_url)
code = input('Paste code here: ')
```

Thanks

**Comment by guybartal** [comment]
happens to me too

**Comment by canine-afficionado** [comment]
Me too - does anyone know how to work around this?

**Comment by tscholze** [comment]
+1. Did somebody found a solution? :)

**Comment by KTibow** [comment]
Everybody, @tfitzhardinge, @guybartal, @b3nda1ley, @tscholze, if you look at the code there are two parts:
> client_secret = 'client_secret'
> client_id='client_id'

You need to register an app in [Azure](https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationsListBlade). I have some docs on how in [my repo about backing up a Raspberry Pi to OneDrive](https://github.com/KTibow/raspberrypi-onedrive-backup). Once you get the creds, you can change those two lines.
If this works, consider closing your issue.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
