### ISSUE TITLE
It doesn't work for that some API is deprecated

### ISSUE THREAD

**Issue by wekan8** [OneDrive/onedrive-sdk-python#141]
I used this code and it has response an error:

response:
{u'error': {u'message': u'The app ID is blocked for access of the O365 Discovery Service.', u'code': u'101, Microsoft.Online.Services.O365Discovery.O365DiscoveryException'}}

https://social.msdn.microsoft.com/Forums/azure/en-US/d640a9ec-09f0-4c75-9883-93d153f6c07d/the-app-id-is-blocked-for-access-of-the-o365-discovery-service?forum=Office365forDevelopers

Office365 Discovery Service was deprecated by Microsoft in Jan 2018: https://developer.microsoft.com/en-us/office/blogs/outlook-rest-api-v1-0-office-365-discovery-and-live-connect-api-deprecation/

"Today, we are announcing the deprecation of the Office 365 discovery service and Office 365 discovery service SDK for .NET in favor of using the Microsoft Graph. Deprecation begins on January 10th, 2018. Newly registered apps will not be able to access the Office 365 discovery service. Existing apps can continue to use the service until November 1st, 2019. From November 1st, 2019 onward, the Office 365 discovery service will be fully decommissioned, and no apps will be able to use the service anymore"

The solution is to use Microsoft Graph APIs.

**Comment by ThibTrip** [comment]
Hi, 

I think I have the same problem as you (see below) when accessing a business account (works fine with a private account though).

`{'error': {'code': '101, Microsoft.Online.Services.O365Discovery.O365DiscoveryException', 'message': 'The app ID is blocked for access of the O365 Discovery Service.'}}
`

I am a bit lost do you have a simple explanation or a ready to execute code somewhere?

I used the code sample provided in README.md and used "http://localhost" as redirect URI (also registered in Azure). I do get a code but also this error and can't use the code anyways.

```
import onedrivesdk
from onedrivesdk.helpers import GetAuthCodeServer
from onedrivesdk.helpers.resource_discovery import ResourceDiscoveryRequest

client_secret = '*******'
client_id='*******'
redirect_uri = 'http://localhost'
discovery_uri = 'https://api.office.com/discovery/'
auth_server_url='https://login.microsoftonline.com/common/oauth2/authorize'
auth_token_url='https://login.microsoftonline.com/common/oauth2/token'

http = onedrivesdk.HttpProvider()
auth = onedrivesdk.AuthProvider(http,
                                client_id,
                                auth_server_url=auth_server_url,
                                auth_token_url=auth_token_url)
auth_url = auth.get_auth_url(redirect_uri)
code = GetAuthCodeServer.get_auth_code(auth_url, redirect_uri)
auth.authenticate(code, redirect_uri, client_secret, resource=discovery_uri)
# If you have access to more than one service, you'll need to decide
# which ServiceInfo to use instead of just using the first one, as below.
service_info = ResourceDiscoveryRequest().get_service_info(auth.access_token)[0]
auth.redeem_refresh_token(service_info.service_resource_id)
client = onedrivesdk.OneDriveClient(service_info.service_resource_id + '/_api/v2.0/', auth, http)
```

response:

```
127.0.0.1 - - [12/Mar/2019 11:53:41] "GET /?code=***&session_state=**** HTTP/1.1" 200 -

{'error': {'code': '101, Microsoft.Online.Services.O365Discovery.O365DiscoveryException', 'message': 'The app ID is blocked for access of the O365 Discovery Service.'}}

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-2-6130989ba125> in <module>
     18 # If you have access to more than one service, you'll need to decide
     19 # which ServiceInfo to use instead of just using the first one, as below.
---> 20 service_info = ResourceDiscoveryRequest().get_service_info(auth.access_token)[0]
     21 auth.redeem_refresh_token(service_info.service_resource_id)
     22 client = onedrivesdk.OneDriveClient(service_info.service_resource_id + '/_api/v2.0/', auth, http)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\onedrivesdk\helpers\resource_discovery.py in get_service_info(self, access_token)
     27         print(response) # added this myself to print error code
     28 
---> 29         service_info_list = [ServiceInfo(x) for x in response['value']]
     30         trimmed_service_info_list = [si for si in service_info_list
     31                                      if si.capability == 'MyFiles' and si.service_api_version == 'v2.0']

KeyError: 'value'
```

**Comment by KTibow** [comment]
It's 2020 and it's working for me, @wekan8. Try regenerating your `client_secret`, `client_id`, and upgrading your installation with
```
pip3 install git+https://github.com/OneDrive/onedrive-sdk-python.git
pip3 install --upgrade git+https://github.com/OneDrive/onedrive-sdk-python.git
```
If this works, consider closing.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
