### ISSUE TITLE
PYINSTALLER attibuteError

### ISSUE THREAD

**Issue by ALEERQUESON2DIAS** [OneDrive/onedrive-sdk-python#142]
Hello,

I have a program source with python v3.7.2 that uses ONEDRIVESDK and works fine using the python interpreter and the source program

CMD------>  **py -3** odacce.py a:/odparm.json QUO
RESULTS-->  Total Size: 115.0GiB, Used: 48.9GiB, Remaining: 66.1GiB, Deleted: 159.6KiB,
                      Your state is: normal
CMD-------> **py -3** odacce.py a:/odparm.json FID od:/DAT/A/file.txt
RESULTS---> file.txt<>file.6EA482G9EM79G808!120935

I am trying to generate an executable through PYINSTALLER. Some actions such as obtaining the QUOTA (previous example) works fine, but access to files show the following error 

CMD------>  **odacce.exe**  a:/odparm.json QUO
RESULTS-->  Total Size: 115.0GiB, Used: 48.9GiB, Remaining: 66.1GiB, Deleted: 159.6KiB,
                      Your state is: normal
CMD------> **odacce.exe** a:/odparm.json FID od:/DAT/A/file.txt
RESULTS--> Traceback (most recent call last):
                    File "odacce.py", line 556, in <module>
                    File "odacce.py", line 442, in do_fid
                    File "odacce.py", line 274, in get_remote_item
                    **AttributeError: 'OneDriveClient' object has no attribute 'item'**
                   [5864] Failed to execute script odacce

The instruction that fails is              f = client.item(drive = 'me', path = path).get()

I suppose I need to manage the "*.spec" file to give special parameters to PYINSTALLER builder tool. I saw some information in member .gitignore ( ignore PyCharm) but I do not know how to translate it effectively for the correct generation of the executable module (.exe).

I have read many similar comments about this error in the last two days, but none of the solutions provided have worked or probably I have not been able to interpret them correctly.

Please, could someone give me some indication on this matter?

Thank you very much and best regards

**Comment by KTibow** [comment]
@ALEERQUESON2DIAS please close your first issue when you open your [second issue](https://github.com/OneDrive/onedrive-sdk-python/issues/145). Also, another technique to get attention is to @mention top contributors like cdmayer, D4N14L, and wiktorn.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
