### ISSUE TITLE
Convert docx to pdf directly at the time of downloading using sdk

### ISSUE THREAD

**Issue by jayesht1996** [OneDrive/onedrive-sdk-python#143]
I have uploaded docx file in my onedrive account and i want to download it as pdf. As per onedrive documentation it is possible to download using .format(pdf) option. But how we can download same using this onedrive-sdk-python.

For downloading i am using following command:- 
client.item(drive='me', id='root').children["nice.docx"].download("nice.docx")

**Comment by KTibow** [comment]
@jayesht1996 the onedrive-sdk is supposed to be simple, so they probably don't have this issue. You can try looking for a Word-parsing API/SDK. If it makes sense, consider closing.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
