### ISSUE TITLE
Desperate trying to generate an executable ...

### ISSUE THREAD

**Issue by ALEERQUESON2DIAS** [OneDrive/onedrive-sdk-python#145]
I have a simplified source to the extreme to use ONEDRIVESDK in accessing OneDRive. The source is the following:

   1 import onedrivesdk
   2 wrkclient = onedrivesdk.OneDriveClient
   3 print("CLASS    wrkclient--> ", wrkclient)
   4 wrkitem = wrkclient.item
   5 print("FUNCTION wrkitem----> ", wrkitem)

This source executes correctly  with the Python interpreter ... 
   P:\>python yyacce.py
   CLASS    wrkclient-->  <class 'onedrivesdk.request.one_drive_client.OneDriveClient'> 
   FUNCTION wrkitem---->  <function item at 0x032B88A0>

But, But when I try to generate an executable with PYINSTALLER... it fails
   P:\>yyacce.exe
   CLASS    wrkclient-->  <class 'onedrivesdk.request.one_drive_client.OneDriveClient'>
   Traceback (most recent call last):
      File "yyacce.py", line 4, in <module>
      wrkitem = wrkclient.item
   AttributeError: type object 'OneDriveClient' has no attribute 'item'
   [4720] Failed to execute script yyacce

I suppose that there is some internal process in ONEDRIVESDK that is hidden from PYINSTALLER, but I can not find how to indicate in the SPEC file the way to load the necessary module(s).

Please, has someone any suggestions about it?

Thank you very much

**Comment by earonesty** [comment]
Looks like there is a file `onedrivesdk/version.txt` that has to be bundled with for distribution in your spec file.   NVM, that's not the least of it.   

Looks like the SDK is doing some funky stuff with modules:

Check this code out in the `version_bridge/__init__.py`

`__all__ = [ os.path.basename(f)[:-3] for f in modules if not os.path.basename(f).startswith('_')]`

There's no way pyinstaller will understand that nonsense.... and it's not necessary at all, an empty __init__.py will suffice normally.

However, a side effect of that craziness is that all of the modules in the folder get imported.   And one of the modules monkey patches OneDriveClient to add the "item" function.

I made a fork called "onedrivesdk-fork".   That should work with pyinstaller.  I also included 2 of the outstanding bugfix pull requests.

See: https://github.com/AtakamaLLC/onedrive-sdk-python

**Comment by earonesty** [comment]
You need to modify the specfile to include `onedrivesdk/version.txt`

**Comment by KTibow** [comment]
@ALEERQUESON2DIAS does the fork fix your issue? Are other people trying to generate an executable? If it makes sense, consider closing.

**Comment by MihajaElrich** [comment]
@earonesty  When you remove these lines, **upload_async** doesn't work anymore, so you can't upload large files

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
