### ISSUE TITLE
Downloading specific sheet from excel 

### ISSUE THREAD

**Issue by jpatel3** [OneDrive/onedrive-sdk-python#147]
I am using [one drive file picker](https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/open-file?view=odsp-graph-online) to open the one drive and select the file from user's drive. Specifically excel and csv files. I would like to download specific sheet from the excel, is there option in the api to do that?

**Comment by KTibow** [comment]
@jpatel3 An Excel file is a single file. You would need to try to find a program to parse Excel files.
Consider closing due to irrelevance.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
