### ISSUE TITLE
README.MD never explains the base_url variable

### ISSUE THREAD

**Issue by shellwhale** [OneDrive/onedrive-sdk-python#149]
Saving and Loading a Session code sample mention a `base_url` variable but never explains it.  
https://github.com/OneDrive/onedrive-sdk-python#saving-and-loading-a-session

What should it contains ? Wouldn't it be `api_base_url` instead ?

**Comment by KTibow** [comment]
@shellwhale Autocomplete says the first parameter is `base_url`, and we do pass in `api_base_url` to that parameter in the rest of the examples. I've passed in `api_base_url` and it worked fine. Consider closing this issue.

**Comment by KTibow** [comment]
Fixed in #174

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
