### ISSUE TITLE
How to upload file to one drive via application without client id and secret key

### ISSUE THREAD

**Issue by AnupamaShukla** [OneDrive/onedrive-sdk-python#150]
Hi,

I have seen so may posts for uploading file to one drive. But If we look at the steps, First mandatory thing I saw is to create App in one drive and generate client id and secret key. This client id and secret key is need to pass as a part of authentication url. Also redirect_uri is also need to specify.

If we manually upload file to onedrive, we just need user name and password and there is no need of any explicit application creation.

My question is, Is there any other way to upload file to onedrive without creating app on onedrive? I mean Just by using authentication prompt for username and password.

TIA

**Comment by andreabisello** [comment]
@AnupamaShukla have you find any solution? i'm searching for the same thing. Due the official onecloud client is not user friendly, and i only want to upload a file, i'm trying to develop my personal upload-client.

**Comment by KTibow** [comment]
@AnupamaShukla that would be insecure. If apps took your user name and password, then they could access all of your Microsoft stuff. This way, when you click on "Accept" the app can only do OneDrive stuff. It may be possible to use Selenium or analyzing the web requests to generate the client ID and secret from account login, but personally I wouldn't give somebody else's app my Microsoft login.
Consider closing as it is very easy to [make an app](https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationsListBlade).

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
