### ISSUE TITLE
AADSTS500201 error

### ISSUE THREAD

**Issue by lsaint** [OneDrive/onedrive-sdk-python#151]
When i run the demo code , the browser  popup a  message box like this:

AADSTS500201: We are unable to issue tokens from this API version for a Microsoft account. Please contact the application vendor as they need to use version 2.0 of the protocol to support this.

how should i do ?

**Comment by KTibow** [comment]
@lsaint nobody else is having that issue. Given that the original makers of this SDK have stopped working on it, consider closing your issue if this isn't a problem anymore.
Given how old your issue is, consider that your version of the library might be outdated. You can install the latest version with
```
pip install git+https://github.com/OneDrive/onedrive-sdk-python.git
```

**Comment by OD1995** [comment]
@lsaint did you get this working in the end? I am getting the same AADSTS500201 error and installing the latest version, as suggested by @KTibow, has not had any impact. I am using the code [here](https://github.com/OneDrive/onedrive-sdk-python#onedrive-for-business).

**Comment by KTibow** [comment]
@OD1995 try out the fork: https://github.com/AtakamaLLC/onedrive-sdk-python

**Comment by OD1995** [comment]
Thanks for the suggestion, @KTibow! Unfortunately, I have received the exact same error using that fork

**Comment by KTibow** [comment]
@OD1995 can you share your exact code? (Just put `***` where the secrets are)

**Comment by OD1995** [comment]
@KTibow 

```
import onedrivesdk_fork as onedrivesdk
from onedrivesdk_fork.helpers import GetAuthCodeServer
from onedrivesdk_fork.helpers.resource_discovery import ResourceDiscoveryRequest

redirect_uri = 'http://localhost:8080'
client_id = "****"
client_secret = "***"
discovery_uri = 'https://api.office.com/discovery/'
auth_server_url='https://login.microsoftonline.com/common/oauth2/authorize'
auth_token_url='https://login.microsoftonline.com/common/oauth2/token'

http = onedrivesdk.HttpProvider()
auth = onedrivesdk.AuthProvider(http,
                                client_id,
                                auth_server_url=auth_server_url,
                                auth_token_url=auth_token_url)
auth_url = auth.get_auth_url(redirect_uri)
code = GetAuthCodeServer.get_auth_code(auth_url, redirect_uri)
auth.authenticate(code, redirect_uri, client_secret, resource=discovery_uri)
# If you have access to more than one service, you'll need to decide
# which ServiceInfo to use instead of just using the first one, as below..
service_info = ResourceDiscoveryRequest().get_service_info(auth.access_token)[0]
auth.redeem_refresh_token(service_info.service_resource_id)
client = onedrivesdk.OneDriveClient(service_info.service_resource_id + '/_api/v2.0/', auth, http)
```

**Comment by KTibow** [comment]
Hmm... I don't know what's going on here. Can you try using the other code with the same ID and secret? Other than that, I can't help you, because I don't have OneDrive for Business.

**Comment by OD1995** [comment]
By other code, do you mean OneDrive code rather than OneDrive for Business code?

**Comment by lsaint** [comment]
> @lsaint did you get this working in the end? I am getting the same AADSTS500201 error and installing the latest version, as suggested by @KTibow, has not had any impact. I am using the code [here](https://github.com/OneDrive/onedrive-sdk-python#onedrive-for-business).

I use Microsoft Graph instead.  Get or Delete a file in OneDrive is what we need, it's simple, it didn't take a lot work by using Microsoft Graph.
