### ISSUE TITLE
Authentication - GetAuthCodeServer without webbrowser.open and http GET stdout

### ISSUE THREAD

**Issue by kchojn** [OneDrive/onedrive-sdk-python#153]
Hi,
Is it possible to authenticate **WITHOUT** 2 things:
- without opening new page - `webbrowser.open(auth_url)` in **GetAuthCodeServer.py**
- without getting GET response on stdout during `code = GetAuthCodeServer.get_auth_code(auth_url, self.__REDIRECT_URI)`; without this print:
![Adnotacja 2019-06-11 171411](https://user-images.githubusercontent.com/43881785/59284318-5ad86b00-8c6c-11e9-92a6-4a76a9a0585d.png)
Would be nice to get only code, without printing response.

I think, it will be very useful. If you know workaround, please, let me know.

**Comment by kchojn** [comment]
One more; is it possible to sign in without having a browser? I would like the user to be able to log in without a browser every time. Connection with params like login, password, client_id, client_secret should allow me to navigate the disk

**Comment by ferstar** [comment]
> Hi,
> Is it possible to authenticate **WITHOUT** 2 things:
> 
> * without opening new page - `webbrowser.open(auth_url)` in **GetAuthCodeServer.py**
> * without getting GET response on stdout during `code = GetAuthCodeServer.get_auth_code(auth_url, self.__REDIRECT_URI)`; without this print:
>   ![Adnotacja 2019-06-11 171411](https://user-images.githubusercontent.com/43881785/59284318-5ad86b00-8c6c-11e9-92a6-4a76a9a0585d.png)
>   Would be nice to get only code, without printing response.
> 
> I think, it will be very useful. If you know workaround, please, let me know.

need this feature too

**Comment by KTibow** [comment]
@ferstar and @kchojn you can run the code on another PC, save the session, and copy it over. Docs [here](https://github.com/OneDrive/onedrive-sdk-python#saving-and-loading-a-session). (The file to copy is called `session.pickle`.)

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
