### ISSUE TITLE
Access shared folder through webapp

### ISSUE THREAD

**Issue by npitsillos** [OneDrive/onedrive-sdk-python#154]
Hello,

I want to ask whether it is possible to access a shared OneDrive folder using the shared link through a webapp with no user interaction whatsoever.  For example by authenticating the webapp using a set of credentials with the API or sdk behind the scenes so the user will be served the shared folder as if they clicked on the shared link.  Is this possible? All methods of accessing require a user interaction at least once.

**Comment by KTibow** [comment]
@npitsillos here's the docs:
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/using-sharing-links?view=odsp-graph-online
You can do the alike as many others and use the `requests` library to do it. Given that the OneDrive SDK is supposed to be simple, if you don't think other people want that functionality, consider closing your issue.
