### ISSUE TITLE
Scopes in tutorial are no longer available. What are the scopes I have to use now?

### ISSUE THREAD

**Issue by tscholze** [OneDrive/onedrive-sdk-python#155]
After May 2019, the "old" Azure AD App API permissions are no longer available. 
I guess this means, that the scopes `['wl.signin', 'onedrive.readwrite']` are no longer available.

What scopes should I use now?

Thanks!

**Comment by KTibow** [comment]
@tscholze It's 2020 and the scopes are still working. Consider closing your issue.
