### ISSUE TITLE
Cant import `Session` to get OneDrive API client object based on customer's access_token.

### ISSUE THREAD

**Issue by remort** [OneDrive/onedrive-sdk-python#156]
It seems that `__init__.py` of onedrivesdk doesn't contain `from .session import Session` anymore, so I can't import `Session` from `onedrive` module.

I need Session class to get able to access to onedrive api upon customer's access_tokens which I handle myself. See https://github.com/OneDrive/onedrive-sdk-python/issues/54

**Comment by remort** [comment]
Imported it like that: `from onedrivesdk.session import Session`. Issue solved.

Would be nice if you document the case with getting `OneDriveClient` with pre-existing access_token.

**Comment by remort** [comment]
Obtaining customer access_token like described here:
https://docs.microsoft.com/en-us/graph/auth-v2-user?context=graph%2Fapi%2F1.0&view=graph-rest-1.0
I am able to use file API via HTTP REST, but get 'unauthenticated - Authentication failed' when try to get onedrivesdk client using this access token. Scope is `files.readwrite.appfolder offline_access`.

**Comment by remort** [comment]
We should use exactly this auth flow:
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/graph-oauth?view=odsp-graph-online#code-flow
with `onedrivesdk` library.
This flow gives proper tokens for this lib.

I solved my issue.

**Comment by KTibow** [comment]
@remort if you solved your issue consider closing or changing your title.

**Comment by remort** [comment]
@KTibow documentation should be updated at least for this issue to be solved.

**Comment by KTibow** [comment]
@remort I'm confused what your issue was. The onedrive-sdk docs work for me.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
