### ISSUE TITLE
Do I have to set a redirect_uri?

### ISSUE THREAD

**Issue by darouwan** [OneDrive/onedrive-sdk-python#158]
I just want to upload some files to onedrive, where I think a url or a web host may be not necessary for me. 

So do I still have to set a redirect_uri?

**Comment by DeSireFire** [comment]
emm...I think yes.
You can have to set a redict_uri by 'https://od.cnbeining.com'

**Comment by darouwan** [comment]
> https://od.cnbeining.com
Hi @DeSireFire 
Thanks for your help.
But when I set od.cnbeining.com as my redirect_uri in my azure app center, it shows:

> Error detail: Redirect URIs must have a common root domain. [dhTKx]

**Comment by darouwan** [comment]
> emm...I think yes.
> You can have to set a redict_uri by 'https://od.cnbeining.com'

Thanks @DeSireFire 
But when I set od.cnbeining.com as my redirect_uri in my azure app center, it shows:

> Error detail: Redirect URIs must have a common root domain. [dhTKx]

**Comment by DeSireFire** [comment]
![image](https://user-images.githubusercontent.com/18726905/62414272-ba8b3b00-b64b-11e9-837f-215bee29db83.png)
try again~
啧，我看了一下你的博客，是国人，我直接说中文好了。
![image](https://user-images.githubusercontent.com/18726905/62414409-5ec1b180-b64d-11e9-9306-584de33807d4.png)
azure注册的应用程序里redirect_uri如图那么写就OK了。
https://od.cnbeining.com
是属于https://github.com/cnbeining/onedrivecmd 项目里的redirect_uri，我偷懒就直接拿来用了。
你注册的应用程序如果登陆验证成功，会跳转到redirect_uri来返回code
例如：
https://od.cnbeining.com/?code=M6633e08d-136c-4124-975e-c3d7910a64b7

**Comment by darouwan** [comment]
@DeSireFire 感谢~之前是没删除之前的配置， 所以显示错误~
现在azure已经那么填写， 但本地启动的时候会报错 [Errno 49] Can't assign requested address

**Comment by darouwan** [comment]
原来我用的是第二种验证方法~现在照着cnbeining那个项目用第一种方法验证， 但仍然报错 Exception: invalid_client

**Comment by darouwan** [comment]
ok 现在第一种验证方式成功了， 但第二种仍然会报
`OSError: [Errno 49] Can't assign requested address
`

**Comment by DeSireFire** [comment]
> ok现在第一种验证方式成功了，但第二种仍然会报
> `OSError: [Errno 49] Can't assign requested address `
我没有这种情况，你用的是商业版的onedrive吗？

**Comment by darouwan** [comment]
@DeSireFire 
现在问题解决了~
主要问题是 第二种验证方式, 不能使用https://od.cnbeining.com作为重定向uri, 而是需要使用localhost

**Comment by DeSireFire** [comment]
> @DeSireFire
> 现在问题解决了〜
> 主要问题是第二种验证方式，不能使用[https://od.cnbeining.com作为重定向uri](https://od.cnbeining.com%E4%BD%9C%E4%B8%BA%E9%87%8D%E5%AE%9A%E5%90%91uri)，而是需要使用localhost

第二种验证方式，是指
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/graph-oauth?view=odsp-graph-online
里的 “Code flow” 吗？

**Comment by darouwan** [comment]
就是readme里面的第二种，不需要复制那个code，可以直接在Web里验证

发自我的华为手机


-------- 原始邮件 --------
主题：Re: [OneDrive/onedrive-sdk-python] Do I have to set a redirect_uri? (#158)
发件人：RaXian
收件人：OneDrive/onedrive-sdk-python
抄送：JF Chen ,Author


@DeSireFire<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDeSireFire&data=02%7C01%7C%7Cc03f00b86ac44bdd61f608d7194d013f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637005690837206567&sdata=kXkgxP8v4kqRXRSzuL1luuDW2pa2YB3EvPxR5hPAJFE%3D&reserved=0>
现在问题解决了〜
主要问题是第二种验证方式，不能使用https://od.cnbeining.com作为重定向uri<https://od.cnbeining.com%E4%BD%9C%E4%B8%BA%E9%87%8D%E5%AE%9A%E5%90%91uri>，而是需要使用localhost

第二种验证方式，是指
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/graph-oauth?view=odsp-graph-online<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fonedrive%2Fdeveloper%2Frest-api%2Fgetting-started%2Fgraph-oauth%3Fview%3Dodsp-graph-online&data=02%7C01%7C%7Cc03f00b86ac44bdd61f608d7194d013f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637005690837216572&sdata=XsqHGeHLxZlqNG2PQEXTL%2F%2Btx7CgDJqYaTghkQTxGaI%3D&reserved=0>
里的 “Code flow” 吗？

**Comment by DeSireFire** [comment]
原来如此，感谢提醒。
因为我看到其他issue有人说这个sdk有些地方淘汰了，所以根据了第一种方的法流程用requests_oauthlib重新构造了一个方法。
第二种方法显然更方便。

**Comment by darouwan** [comment]
是的~ 第二种更像正常的oauth验证过程, 不知道只是Onedrive这样, 还是微软其他服务都这样

**Comment by KTibow** [comment]
@darouwan I don't speak Chinese, but basically you do need to set the redirect_uri. When it authenticates you, it redirects to that. Set the redirect_uri to `http://localhost:8080/`. Please consider closing your issue.

**Comment by meetchandan** [comment]
Hello @KTibow 
I think we need to mention redirect_uri in the code?

`auth_url = client.auth_provider.get_auth_url(redirect_uri)`

#this will block until we have the code

`code = GetAuthCodeServer.get_auth_code(auth_url, redirect_uri)`


so what should be the value of it. My goal is just to access few files of my client's onedrive in python.
I am not sure what is the use of redirect_uri here. I have client_id and client_secret.

When I try to set any localhost address in the redirect_uri - it says can't assign requested address.
I am running this in k8s pod

**Comment by KTibow** [comment]
just so you know, I can't help you; the last time I worked on this was a year ago, and all of my knowledge is gone

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
