### ISSUE TITLE
Any easy way to upload a file to a specific directory?

### ISSUE THREAD

**Issue by darouwan** [OneDrive/onedrive-sdk-python#160]
I am willing to upload a file to a specific directory, like upload new.txt to new_dir/new.txt
However, it seems I must find the directory id firstly then upload the file.
Is there any convenient way to implement it?

**Comment by KTibow** [comment]
@darouwan, try using this code instead:
```python3
client.item(drive='me', path="new_dir/new.txt").upload("new.txt")
```
Consider closing your issue.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
