### ISSUE TITLE
Discovery API deprecation impact

### ISSUE THREAD

**Issue by sumurthy** [OneDrive/onedrive-sdk-python#162]
The discovery API is being deprecated. Please upgrade the SDK or mark as not supported. 

Refer here for details: https://developer.microsoft.com/en-us/office/blogs/upcoming-deprecation-of-discovery-service-api/

**Comment by KTibow** [comment]
It's 2020 and it still works, @sumurthy. Consider closing.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
