### ISSUE TITLE
Unable to install via pip on MacOS Mojave 10.14

### ISSUE THREAD

**Issue by gmagannaDevelop** [OneDrive/onedrive-sdk-python#163]
I wanted to install onedrive-sdk to manage my files on OneDrive. I created a conda environment with Python 3.5 with the following modules: 

1. pip
2. requests
3. pillow

I proceeded to run:
`pip install onedrivesdk`

Which threw the following **error**:

Collecting onedrivesdk
  Using cached https://files.pythonhosted.org/packages/b3/76/9a3fe5b36079f5c40b33c89ad6f7737e3b8609010a80c9ed24d762ddb93e/onedrivesdk-2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/90/h42xgbnd22x3c6fs9kkb2x680000gn/T/pip-install-7zlfo9w0/onedrivesdk/setup.py", line 9, in <module>
        with open(NOTICE, 'r', encoding='utf-8') as f:
    NotADirectoryError: [Errno 20] Not a directory: '/private/var/folders/90/h42xgbnd22x3c6fs9kkb2x680000gn/T/pip-install-7zlfo9w0/onedrivesdk/setup.py/../NOTICE.rst'

I do not understand how pip works internally, why does it want to use that cached address, or why is it trying to access that unexistent directory on my system.

About my hardware and config:

`brew config` 
HOMEBREW_VERSION: 2.1.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: 925ec737fba1db97d0170c56de982900711cacd3
Last commit: 11 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c637adf2f778c349063c431f52d51ff0421b20f3
Core tap last commit: 14 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 10.0 build 1001
Git: 2.18.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 10.0.1, 1.8.0_172
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 10.3
CLT headers: 10.3.0.0.1.1562985497
XQuartz: 2.7.11 => /opt/X11

**About this mac**
MacBook Pro (13-inch, mid 2012)
Processor: 2.5 GHz Intel Core i5
RAM: 8 GB 1600 MHz DDR3

**Comment by EbrahimKaram** [comment]
I have the same error popping up. But I'm trying to install the package on  raspberry pi via python3

I currently have 
pip=19.2.3
Python=3.7.3

Raspberry pi is raspbian buster

**Comment by Liz4v** [comment]
I had the same problem. Upon further investigation, I discovered that the currently-available PyPI package has absolutely nothing to do with this repository; it now has a no-op deprecation notice that doesn't even work and is otherwise empty.

This applies to all platforms.

**Comment by asiron** [comment]
Same problem on Ubuntu 18.04

**Comment by EbrahimKaram** [comment]
> I have the same error popping up. But I'm trying to install the package on raspberry pi via python3
> 
> I currently have
> pip=19.2.3
> Python=3.7.3
> 
> Raspberry pi is raspbian buster

I ended up just using the requests Oauth Library
https://requests-oauthlib.readthedocs.io/en/latest/
And I read the docs for the microsoft Graph API
https://docs.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-1.0&tabs=http

**Comment by HemabhKamboj** [comment]
Having the same issue on Ubuntu 18.04

**Comment by gmagannaDevelop** [comment]
So there's no answer or support for this sdk?
Will it ever be?

If there's no plan to fix it or update, I'd like to have some news from the team working on it.

Why is there a package on PyPI with the same name but no relation to this repo?

**Comment by ricdea** [comment]
I had the same on a Raspberry Pi but the following worked:

`pip3 install git+https://github.com/OneDrive/onedrive-sdk-python.git`

**Comment by gmagannaDevelop** [comment]
@ricdea You're right. Installing giving the github repo works. Marking this as closed.

**Comment by billzhong** [comment]
Install from github repo is not the solution. Any plan to fix pip install? 
@gmagannaDevelop This issue should keep it open.

**Comment by ddacunha** [comment]
@billzhong the question then is: Is this repo being maintained?

**Comment by billzhong** [comment]
@ddacunha I don't think so. I end up making my own by using requests.
