### ISSUE TITLE
OneDrive for Business - New Apps will not work due to Office 365 Discovery API Deprecation

### ISSUE THREAD

**Issue by Suryaphalle** [OneDrive/onedrive-sdk-python#164]
Hi,

I was started using onedrivesdk for uploading and downloading files to the one drive personal account. I was able to upload and download files using same sdk.
But when i used same sdk for  business account it shown me error.

The error message you get in the console unfortunately and frustratingly buries the underlying error, which I had to debug through to find. The actual error message turns out to be:

"message" : "The app ID is blocked for access of the O365 Discovery Service."
"code" : "101, Microsoft.Online.Services.O365Discovery.O365DiscoveryException"

After seraching for problems solution come to know the discovery api 
'https://api.office.com/discovery/' is being deprecated. 

So i want to know that, how can I access my business account using sdk.

**Comment by earonesty** [comment]
Onedrive for business cannot, trivially, use the sdk.   While it is actually possible to use the graph api as the base url, and get some stuff to work.... not enough will work that you can do anything meaningful.   Use requests and requests_oauthlib directly... works much better, and the graph api is documented pretty well.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
