### ISSUE TITLE
example code. raw_input() is from Python 2

### ISSUE THREAD

**Issue by philshem** [OneDrive/onedrive-sdk-python#165]
Regarding this sample code:
https://github.com/OneDrive/onedrive-sdk-python/blob/master/README.md#onedrive

Python3 uses `input()` in place of `raw_input()`

**Comment by KTibow** [comment]
Fixed in #174

**Comment by KTibow** [comment]
Duplicate of #148

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
