### ISSUE TITLE
Error while installing on Google Colab

### ISSUE THREAD

**Issue by zain910128** [OneDrive/onedrive-sdk-python#166]
When i use the install command on google Colab, i get the following error:
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by jkmartindale** [comment]
This library is deprecated, and the [latest version on PyPI](https://pypi.org/project/onedrivesdk/) is a stub that says it's deprecated:
![image](https://user-images.githubusercontent.com/11380394/70946284-2a56fc80-2014-11ea-8eb9-4e8f93a6216e.png)

You can either install the latest real version of the library with
```sh
!pip install "onedrivesdk<2"
```

Or install the community fork [onedrivesdk-fork](https://pypi.org/project/onedrivesdk-fork/), which has bug fixes that never got merged in.

**Comment by KTibow** [comment]
@zain910128 @jkmartindale is this issue closed? I agree this is a problem that Microsoft needs to fix.

**Comment by jkmartindale** [comment]
This issue will not be resolved as this is a deprecated/abandoned library. Use the workaround above.

No idea if that means this issue should be closed because no code change is "required" or if it should stay open so more people can find the workaround.

**Comment by zain910128** [comment]
I think keep it open since the problem hasn't been fixed officially.
Plus, others can find the work around.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
