### ISSUE TITLE
ImportError: 'onedrivesdk' has been deprecated.

### ISSUE THREAD

**Issue by username7171** [OneDrive/onedrive-sdk-python#169]
so basically this repository should be achieved?

**Comment by KTibow** [comment]
I don't get that error, @AronWater. Make sure you installed this library, not [the deprecated version](https://github.com/mk-fg/python-onedrive/blob/master/doc/api.md). You may be able to upgrade by running
```
sudo pip3 install git+https://github.com/OneDrive/onedrive-sdk-python.git
sudo pip3 install --upgrade git+https://github.com/OneDrive/onedrive-sdk-python.git
```
If this fixed your issue, consider closing it.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
