### ISSUE TITLE
unbound method load_session()

### ISSUE THREAD

**Issue by rwecho** [OneDrive/onedrive-sdk-python#17]
```
client.auth_provider.load_session()
```

Gives an error:

```
TypeError: unbound method load_session() must be called with Session instance as first argument (got nothing instead)
```

the auth_provider's load_session funtion :

```
    def load_session(self, **load_session_kwargs):

        self._session = self._session_type.load_session(**load_session_kwargs)
```

I don't know how to reslove it.
please help me .

**Comment by cdmayer** [comment]
This sounds like a bug that I already fixed! In the line above `load_session(...)` do you have the decorator `@staticmethod`? If not, then you may have a slightly dated version of the SDK. Unfortunately, it looks like that bug fix didn't make it into the latest release. There is a new release coming soon that will include this bug fix, but until then you can reference the instructions below on how to update your local version of the SDK manually. 
1. Open `{python_install_dir}\Lib\site-packages\onedrivesdk\session.py`
2. Add the highlighted line on [this page](https://github.com/OneDrive/onedrive-sdk-python/blob/master/src/onedrivesdk/session.py#L89) and save the file

You should be good to go after that. Let me know if that doesn't work. Sorry for the inconvenience.

**Comment by rwecho** [comment]
thank you,It  works now.
