### ISSUE TITLE
Async uploads are blocking but async downloads are not

### ISSUE THREAD

**Issue by KTibow** [OneDrive/onedrive-sdk-python#173]
You can get by this by running an async upload on a different thread or using 
> ```python
> import asyncio
> # Make sure you've authenticated
> def download(client, drivename, localname):
>     loop = asyncio.get_event_loop()
>     loop.run_until_complete(client.item(drive='me', path=drivename).download_async(localname))
> 
> download(client, "largefile.whatever", "downloadedfile.whatever")
> ```
but this is odd behavior that should probably be fixed.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
