### ISSUE TITLE
Mark labels

### ISSUE THREAD

**Issue by KTibow** [OneDrive/onedrive-sdk-python#175]
I've been browsing through these issues, and there's a lot of duplicates, enhancements, and outdated/invalid issues. It would really help a lot of people to apply those three labels. If anybody who can wants to help, I think a lot of people would like it.

**Comment by KTibow** [comment]
Can somebody please mark this as a enhancement?

**Comment by KTibow** [comment]
Some groups of issues that are duplicates are installation issues and Office-format related issues, just to give you a head start, @cdmayer @D4N14L and @wiktorn.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
