### ISSUE TITLE
ImportError: 'onedrivesdk' has been deprecated.

### ISSUE THREAD

**Issue by qo4on** [OneDrive/onedrive-sdk-python#182]
What is the right way to upload, download files and create folders in Onedrive? Is there a Python library availiable today?

**Comment by KTibow** [comment]
@qo4on try doing a `pip freeze`, then `pip uninstall` anything that sounds related to OneDrive.  
Then install the more maintained fork with `pip install onedrivesdk_fork`.  
One you're done, instead of `import onedrivesdk` use `import onedrivesdk_fork as onedrivesdk`.

**Comment by qo4on** [comment]
Thanks! Is there any official python API for Onedrive?

**Comment by KTibow** [comment]
This is the official API, it's just the original maintainers stopped maintaining it. `onedrivesdk_fork` *is unofficial*, but it's currently maintained, and it's your best bet as it was based off of the original one. Of course you can also look at the official API docs and just use `requests` to manually talk to the API.

**Comment by qo4on** [comment]
Do you know where to find example of Onedrive authentication using `requests`?

**Comment by KTibow** [comment]
Here's `onedrivesdk_fork`s opinion:
  
==================
  
  
If you are looking for an alternative api, consider using one of:
- requests-oauthlib for OAuth and requests + .json() for the direct REST calls
- authomatic

(Personally, I believe that the onedrivesdk needs a replacement with less marshalling and more documentation.)

**Comment by RasyidMF** [comment]
Same problem, but my solution is this command
```bash
pip install onedrivesdk<2
```

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
