### ISSUE TITLE
Cant Authenticate

### ISSUE THREAD

**Issue by HiToshiNakamoto** [OneDrive/onedrive-sdk-python#183]
I'm a OneDrive Business User 
im able to install one driveSDK
but im not able to go any further to authenticate
![image](https://user-images.githubusercontent.com/76832402/104926502-3f941c80-59c6-11eb-8517-748e73c3f795.png)
stuck here :-
![image](https://user-images.githubusercontent.com/76832402/104926552-50dd2900-59c6-11eb-924b-573d411a8a4d.png)

**Comment by KTibow** [comment]
Looks like you're new to Python. I'd recommend you do some more research before you start. Your error is that before running, you're supposed to replace `your_client_id` with your client id, and `client_secret` with your client secret. Get them in Azure.

**Comment by jakiyaa** [comment]
you need to type your client id and client secret 

 get client id and client secret in https://portal.azure.com/

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
