### ISSUE TITLE
activityApi missing?

### ISSUE THREAD

**Issue by username7171** [OneDrive/onedrive-sdk-python#184]
seems this repo is for uploading, downloading, editing.

Is there an activity monitoring API of onedrive in python?  Thanks!

**Comment by KTibow** [comment]
This repo isn't very maintained. What do you want to do?

**Comment by username7171** [comment]
> This repo isn't very maintained. What do you want to do?

to see recent activity of a user manipulating the files. such as upload, download, edit .

Google provide this in https://developers.google.com/drive/activity/v2

**Comment by KTibow** [comment]
Try looking directly at their API.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
