### ISSUE TITLE
How to get metadata of file or directories like size,modified or creation time,etc?

### ISSUE THREAD

**Issue by Gorparth** [OneDrive/onedrive-sdk-python#185]
client.item(id=item_id).
i've client and item id wanna get size and time.
please reply fast as project deadline is coming

**Comment by KTibow** [comment]
This repo is abandoned. Anyway, could you elaborate on what you want do do? Try using autocomplete to look for functions (I know IDLE supports it).

**Comment by Gorparth** [comment]
i got it it was just item name .get() and then .size.  e.g client.item(id=item_id).get().size
