### ISSUE TITLE
 OneDrive for Business Cant Authenticate (error GetAuthCodeServer)

### ISSUE THREAD

**Issue by jakiyaa** [OneDrive/onedrive-sdk-python#187]
![Screenshot 2021-04-06 172312](https://user-images.githubusercontent.com/67457538/113707507-a095db80-96fd-11eb-901e-ef21dc604fba.png)

working fine for onedrive personal  but **not working in OneDrive Business  cant get auth link**
 

my python instalation>
![Screenshot 2021-04-06 172527](https://user-images.githubusercontent.com/67457538/113707683-e05cc300-96fd-11eb-8cbe-6114f619f27e.png)

my app registrations>

![Screenshot 2021-04-06 173430](https://user-images.githubusercontent.com/67457538/113710878-e0f75880-9701-11eb-9b72-9b72fc7d4e0b.png)

![Screenshot 2021-04-06 173331](https://user-images.githubusercontent.com/67457538/113708546-fb7c0280-96fe-11eb-8088-d39b98a6e8b7.png)

![Screenshot 2021-04-06 173231](https://user-images.githubusercontent.com/67457538/113708564-ffa82000-96fe-11eb-8bf2-d111e26a9bfc.png)

what's the problem?  GetAuthCodeServer  error?

**Comment by KTibow** [comment]
Please give the full traceback.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
