### ISSUE TITLE
LocalHost refuse to connect

### ISSUE THREAD

**Issue by acmilannesta** [OneDrive/onedrive-sdk-python#190]
Hi, 

I'm trying to OAuth2 and set up redirect URL as following:
![image](https://user-images.githubusercontent.com/47703762/115299730-2f0e5200-a12d-11eb-9963-31b0010dabe0.png)

Here is my code:
```
import onedrivesdk_fork as onedrivesdk
redirect_uri = 'http://localhost:8080/'
client_secret = 'xxxx'
client_id = 'xxxx'
api_base_url='https://api.onedrive.com/v1.0/'
scopes=['wl.signin', 'wl.offline_access', 'onedrive.readwrite']

http_provider = onedrivesdk.HttpProvider()
auth_provider = onedrivesdk.AuthProvider(
    http_provider=http_provider,
    client_id=client_id,
    scopes=scopes)

client = onedrivesdk.OneDriveClient(api_base_url, auth_provider, http_provider)
auth_url = client.auth_provider.get_auth_url(redirect_uri)
print(auth_url)
```
But once I click the ```auth_url``` and select "yes" to allow access of all the scopes. Then the localhost refuse to connect.

**Comment by KTibow** [comment]
*sighs* Vague descriptions never help in an issue. Please give a more exact error, and a screenshot.

**Comment by acmilannesta** [comment]
Yes, I just try to automate file uploads to my OneDrive. So when I try to access my account, the authentication page should be direct to the "auth_url" right, but it fails to connect after I click it.
```
https://login.live.com/oauth20_authorize.srf?client_id=6d2489de-a647-47f2-8c46-2c9b2fa113da&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&scope=wl.signin+wl.offline_access+onedrive.readwrite
```

And shows the following
![image](https://user-images.githubusercontent.com/47703762/115410280-7eea2900-a1c0-11eb-82b4-335bdf4a7ac8.png)

**Comment by KTibow** [comment]
Did you see the example base codes? Do any of them work?

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
