### ISSUE TITLE
How to create empty file of any extension ??

### ISSUE THREAD

**Issue by Gorparth** [OneDrive/onedrive-sdk-python#191]
i want to create new file using python, where we have to just give filename with an extension and blank file is created, I'm trying with item  
    path="/tmp.txt"
    item = onedrivesdk.Item()
    item.name = os.path.basename(path)
    item.size = 0
    item.file = onedrivesdk.File()
    client.item(path=os.path.dirname(path)).children.add(item)

but this is giving error: onedrivesdk.error.OneDriveError: invalidRequest - Cannot create a file without content

and I want it to be of any extension.
Please help

**Comment by KTibow** [comment]
Try `File("")`

**Comment by Gorparth** [comment]
doesn't seem to work, can you provide full function like aforementioned ?

**Comment by KTibow** [comment]
Try `item.file = onedrivesdk.File("")`. However this may be a limitation with the API you can't change. Have you tried [googling](https://lmgtfy.app/?q=how+to+create+empty+file+onedrive+API) it yet?

**Comment by Gorparth** [comment]
I used this item.file = Fil(""), and it is not giving error but when I'm adding this item(empty file) to the parent folder's childern list that time it is showing error  that can not add item.


Therefore I was asking for full function like what would be the steps to create file, like I've used this but something is wrong.

path="/tmp.txt"
item = onedrivesdk.Item()
item.name = os.path.basename(path)
item.size = 0
item.file = onedrivesdk.File("")
client.item(path=os.path.dirname(path)).children.add(item)

**Comment by KTibow** [comment]
Let me say that again:

> Have you tried [googling](https://lmgtfy.app/?q=how+to+create+empty+file+onedrive+API) it yet?

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
