### ISSUE TITLE
is there search function and resolve function? 

### ISSUE THREAD

**Issue by Gorparth** [OneDrive/onedrive-sdk-python#192]
searching with name of file or folder and is there any function which is same as resolve function which was in previous version
?

**Comment by KTibow** [comment]
What?
Could you try to elaborate and use better grammar? Also, could you add examples/links/screenshots?

**Comment by Gorparth** [comment]
Ya, is any search function in onedrivesdk, searching item based on mime_type? 
Searching with specific name that may be either folder or file

Like I want to search example.pdf and mime type pdf ( just for example) 

So how can I do that with onedrivesdk ?

I've written one search function but it is time consuming, if there is any search function in onedrivesdk only then it may be with less time complexity.

**Comment by Gorparth** [comment]
Resolve function gives id of the file from path, in previous there was fun cation named resolve, but in newer api doesn't have that but I found something similar to that 

client.item(path=path).get().id

**Comment by KTibow** [comment]
Is that possible with the plain API?

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
