### ISSUE TITLE
Possible to upload large files to One Drive same file?

### ISSUE THREAD

**Issue by yeric1789** [OneDrive/onedrive-sdk-python#193]
Hi,

I have a question regarding the way in which cloud storage could be uploaded to OneDrive. My organization has a OneDrive account and large amounts of storage on that one drive account. I currently have a script that writes each video frame to a txt file on my own hard drive in my physical computer like so:

```
for _, frame_compressed in dict_store_frames.items():
      frame_header_byte_length = frame_compressed[2].to_bytes(INT_BYTE_SIZE, 'big') 
      with open(frame_compressed[0], 'ab') as fp:
                fp.write(frame_header_byte_length + frame_compressed[1])
```

instead of frame_compressed[0] being a path on my hard drive I would like it to be a path to a specific file in OneDrive and to not have any of the video files stored on my local machine but rather only on OneDrive. 
These files are rather large (each being 70GB or greater) and are written in small chunks of around 2MB per frame. Would this be possible? How would I go about doing this on a machine. Any help that could be provided would be greatly appreciated. Thanks.

**Comment by KTibow** [comment]
Could you clarify what you mean by

> Possible to upload large files to One Drive same file?

?
