### ISSUE TITLE
what to set as redirect_uri to generate clientId and clientSecret?

### ISSUE THREAD

**Issue by meetchandan** [OneDrive/onedrive-sdk-python#194]
Sorry, this is not an issue - But I am unable find some good documentation on how to generate client Id and client secret to access onedrive.

The documentations I went through required me to enter a redirect_url, which is not relevant in my case. I just want to download and upload few files regularly to onedrive using python.
So I am not sure what redirect URL should I put.

Any help would be highly appreciated.

**Comment by KTibow** [comment]
As the guy who unofficially maintains this repository, here's a quick explanation: https://github.com/KTibow/pi-DriveUp#authentication for how to get the client id and secret.

The redirect URI is unrelated from the client id and secret. Just keep it as localhost. Let me know if you need any more help.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
