### ISSUE TITLE
How to access file from a certain folder

### ISSUE THREAD

**Issue by ekaterinaterzieva** [OneDrive/onedrive-sdk-python#195]
I only see examples with the root folder, how can I access other folders in my onedrive?

**Comment by KTibow** [comment]
You should be able to just add the folder name first.

**Comment by ekaterinaterzieva** [comment]
Can you give me an example of what's the right way to write the request because I tried in multiple ways and I keep getting different errors?

**Comment by RasyidMF** [comment]
Follow my code example :  

```python
folder = client.item(path="/YOUR_PATH")
```

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
