### ISSUE TITLE
invalid_client error when authenticating

### ISSUE THREAD

**Issue by yuedai0531** [OneDrive/onedrive-sdk-python#196]
I keep getting invalid_client error when authenticating.
I went on Azure portal > App registrations and created an app. The client ID i am using is `Application (client) ID` that you find in the overview. I also created a client secret in `Certificates & secrets`.

Here are the error details:
> client.auth_provider.authenticate(code, redirect_uri, client_secret)
  File "onedrivesdk_fork/auth_provider.py", line 200, in authenticate
    response = self._http_provider.send(method="POST",
  File "onedrivesdk_fork/http_provider.py", line 71, in send
    custom_response = HttpResponse(response.status_code, response.headers, response.text)
  File "onedrivesdk_fork/http_response.py", line 61, in __init__
    raise Exception(str(message["error"]))
Exception: invalid_client

**Comment by yuedai0531** [comment]
more details on the error.
![image](https://user-images.githubusercontent.com/26657972/141862515-d222f4c0-723a-47be-a801-e4f25a9f660a.png)

**Comment by yuedai0531** [comment]
The error was with the client_secret
I was using client secret ID instead of Value
![image](https://user-images.githubusercontent.com/26657972/141864510-cd1c9de6-0c5b-4a57-8238-fe1424c505d5.png)

**Comment by smartcmsteam** [comment]
> The error was with the client_secret I was using client secret ID instead of Value ![image](https://user-images.githubusercontent.com/26657972/141864510-cd1c9de6-0c5b-4a57-8238-fe1424c505d5.png)

it works perfect, many thanks.
