### ISSUE TITLE
How to upload an item to onedrive

### ISSUE THREAD

**Issue by Dskpupper** [OneDrive/onedrive-sdk-python#198]
![image](https://user-images.githubusercontent.com/64250511/144797650-690be067-4e6a-4d89-822a-d4177b8f9632.png)
Does this mean its authenticated? 
Also how do i upload an excel file to  my onedrive account using this coomand
returned_item = client.item(drive='me', id='root').children['newfile.txt'].upload('./path_to_file.txt')

"newfile.txt" is my file name and  " path_to_file" is C:\users\downloads.
Do i need to provide values to drive and id?
Thanks

**Comment by KTibow** [comment]
Welcome, adventurer. This is a forgotten land, and I am the only one who dares to help around here. However, I can't understand your question at all. What are you trying to do, what code did you use (share all of your code, with ``` formatting), and what happened instead?

**Comment by Dskpupper** [comment]
I am not able to connect to local host , I tried both methods given in the repo
<img width="956" alt="image" src="https://user-images.githubusercontent.com/64250511/146097457-b5cd2705-5bec-44f6-a950-079e372950c9.png">
<img width="823" alt="image" src="https://user-images.githubusercontent.com/64250511/146097551-247dd63d-467a-4bd7-aa4c-cf2f40ea45b9.png">
i get the microsoft login web page when i click the auth_url , but it local host doesnt connect .

My goal is , I need to connect OneDrive to AWS databricks using python script so i can read download files. Basically want onedrive accessible in databrikcs .

**Comment by KTibow** [comment]
>  but it local host doesnt connect .

That's intentional. Did you even read the text?
"Copy everything in the address bar after "code=", and paste it below."

**Comment by KTibow** [comment]
@Dskpupper were you able to get your code to work? I'm happy to help.
