### ISSUE TITLE
Accessing a different OneDrive account

### ISSUE THREAD

**Issue by jkim8256** [OneDrive/onedrive-sdk-python#199]
Hi, how can I access another OneDrive account if I allowed access for an account already? Is there a way to disconnect the current access?

**Comment by KTibow** [comment]
Please elaborate as much as you can, because I can't really understand what you mean right now.

**Comment by jkim8256** [comment]
So i was able to get authentication and do things like adding a folder to my onedrive. (Everything is good) But, for example, if i want to add a folder to another onedrive account(not the one i am connected to right now) is there a way to do that?

Hopefully this makes it clearer

**Comment by KTibow** [comment]
You'll need to get a different key from [Azure](https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationsListBlade).
