### ISSUE TITLE
Onedrive for business

### ISSUE THREAD

**Issue by jkim8256** [OneDrive/onedrive-sdk-python#200]
Hi, while i was working with onedrive for business account to gain access and use the api, then i ran into a problem.
![20220113_104320](https://user-images.githubusercontent.com/77354951/149362495-2bdb62a0-9f9d-4008-98e0-0828157b4a10.jpg)

![20220113_104621](https://user-images.githubusercontent.com/77354951/149362513-12f4e5c4-7eb4-4eda-8f95-3b1c3699cbce.jpg)

Here are the code and traceback. I have been reading it for a while now, but all i understood is that api.office.com is having a connection issue.

Could i get some help? Thanks in advance for your time!

**Comment by KTibow** [comment]
It means it couldn't connect to the Office API. Make sure you have a working internet connection and DNS.

**Comment by jkim8256** [comment]
Thank you for the reply! 
However, I am very sure that I had a working internet connection when I was running the program. I am not sure what you mean by DNS though. (The link to the office API ("discovery_uri" I believe) was from the example from this GitHub readme page. Also, the "https://api.office.com" was not reachable when I tried to connect to it.)
![Capture](https://user-images.githubusercontent.com/77354951/149629511-b59df834-b52c-499d-85b2-25a98093be75.PNG)
 
Is the api page deprecated or something? Or am I just not understanding things?
Again, thanks in advance for your time and help!

**Comment by KTibow** [comment]
Sad news: Our beloved repo is becoming discontinued.
https://devblogs.microsoft.com/microsoft365dev/outlook-rest-api-v2-0-deprecation-notice/
It sounds like you'll have to manually work with the API using the `requests` library.

**Comment by jkim8256** [comment]
Sorry for the late reply. So does that mean I cannot use the OneDrive for business example code as it uses the outlook rest API v2.0 and thus I need to use requests library somehow(idk how to use them yet) to replace the soon-to-be-deprecated rest API?

Or does that mean this whole repository "onedrive-sdk-python" is being discontinued due to the MS rest API being discontinued soon?

I assume the former is right rather than latter, but just to make sure.
And always, thank you so much!

**Comment by KTibow** [comment]
This library will no longer work (the code will probably stay there) for business, and possibly stop working for personal.
All the library did was talk to the API for you, and you can directly talk to the API using the `requests` library.
This [updated version](https://github.com/AtakamaLLC/onedrive-sdk-python) may/may not work.

**Comment by yyqi17** [comment]
Hi, have you solved this problem connecting to OneDrive for business?

**Comment by KTibow** [comment]
This SDK is abandoned.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
