### ISSUE TITLE
Mounting OneDrive to Google Colab

### ISSUE THREAD

**Issue by erguntiryaki** [OneDrive/onedrive-sdk-python#202]
Dear OneDrive SDK Team,

I am working on Google Colab and want to use my storage on OneDrive.  Mounting Google drive is very handy when working in Colab. Is it possible to mount OneDrive to Colab? Is there a code example that I can use?

To mount Google Drive:
`from google.colab import drive` 
`drive.mount('/content/gdrive/)`

Any help will be greatly appreciated. Thank you so much.

**Comment by KTibow** [comment]
> Dear OneDrive SDK Team,

The bad news is that the people you speak of basically no longer exist. This is a dead repo. However, you could probably figure out how to download or upload data with this library; make sure you have something like VS Code's Intellisense to autocomplete and show you docstrings. As far as I know, you can't "mount" Onedrive. If you need me to elaborate, let me know.

**Comment by erguntiryaki** [comment]
Hello @KTibow,  thank you so much for the kind reply. I will try to figure it out as you suggest.

Cheers,

**Comment by aissak21** [comment]
HI @erguntiryaki Same query here. Have you gotten anything that works?

**Comment by Rushikesh-Malave-175** [comment]
you can mount onedrive actually
you need to use rclone. 
here are 2 videos that i watched to mount onedrive: https://youtu.be/8_lsEAKJv8c , https://youtu.be/U6YPgARhRzA

**Comment by Rushikesh-Malave-175** [comment]
hope im not too late

**Comment by Longhuiberkeley** [comment]
@Rushikesh-Malave-175 I am trying to mount OneDrive onto my Colab project. Thanks for your effort to reply

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
