### ISSUE TITLE
List and download subfolders and files in a publicly shared directory

### ISSUE THREAD

**Issue by dutta-alankar** [OneDrive/onedrive-sdk-python#207]
Hi,

I have a publicly shared link accessing which requires no authentication. I want to list all the contents in this directory and its sub-directories and download the files one by one. How to do this using `onedrive-sdk-python`? I am a newbie in this. Please help.

Link: [https://indianinstituteofscience-my.sharepoint.com/:f:/g/personal/alankardutta_iisc_ac_in/EhdL9SYY45FOq7zjrWGD0NQBcy3pn6oTP2B9pGhxPwLnkQ?e=E956ug](https://indianinstituteofscience-my.sharepoint.com/:f:/g/personal/alankardutta_iisc_ac_in/EhdL9SYY45FOq7zjrWGD0NQBcy3pn6oTP2B9pGhxPwLnkQ?e=E956ug)

**Comment by twmht** [comment]
@dutta-alankar 

do you know how to do that?

**Comment by dutta-alankar** [comment]
No! I couldn't figure this out. I generated individual links for every item and appended ?download=1 at the end of the links.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
