### ISSUE TITLE
Request: Upload function using data instead of path

### ISSUE THREAD

**Issue by Stullemon** [OneDrive/onedrive-sdk-python#23]
Hey Microsoft,

I am looking into uploading entire zip-files from local folders created just in time. I can obviously write a temporary file, upload it and then delete it again. However, this is associated with some IO lag and puts some stress on the drive. Something which I would like to avoid when executing my python script on a portable flash drive or a rather slow HDD (possibly further slowed down by antivirus software). Hence, I had the idea to use an in memory zip file (see http://stackoverflow.com/questions/2463770/python-in-memory-zip-library ).

However, this possibility is obstructed by the the upload function of the SDK, which - to the best of my knowledge - only supports path but not data. Unfortunately, I lack the skill to effectively and generically extend the SDK myself. 

Thus my request to introduce the possibility to use data instead of path for the upload function. What do you think?

Regards,
Stulle

**Comment by Stullemon** [comment]
I just noticed, this might actually relate to #14

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
