### ISSUE TITLE
OneDrive for Business / list exception KeyError: 'value'

### ISSUE THREAD

**Issue by jjbrink** [OneDrive/onedrive-sdk-python#26]
following the instructions in issue #16 i'm attempting to connect to onedrive for business and list the items in the root, but get an exception when attempting the list. is there something i'm doing incorrectly?

```
import onedrivesdk

client_id = '17a...'
client_secret = 'RKa...'
redirect_uri = 'https://localhost:...'
onedrive_base_url = 'https://...-my.sharepoint.com/_api/v2.0'

auth_scopes = [ 'wl.signin', 'wl.offline_access', 'onedrive.readwrite' ]


# using this technique b/c i'll need a custom Session class once this is working
http_provider = onedrivesdk.http_provider.HttpProvider()
auth_provider = onedrivesdk.auth_provider.AuthProvider(http_provider=http_provider,
                                                       client_id=client_id,
                                                       scopes=auth_scopes)
client = onedrivesdk.OneDriveClient(onedrive_base_url, auth_provider, http_provider)

# code obtained from logging in on browser
code = "M66..."
client.auth_provider.authenticate(code, redirect_uri, client_secret)

client.item(drive="me", id="root").children.get()

# this last call raises:
#
#Traceback (most recent call last):
#  File "onedrive_test.py", line 54, in <module>
#    client.item(drive="me", id="root").children.get()
#  File "/Library/Python/2.7/site-packages/onedrivesdk/request/children_collection.py", line 131, in get
#    return self.request().get()
#  File "/Library/Python/2.7/site-packages/onedrivesdk/request/children_collection.py", line 72, in get
#    return self._page_from_response(collection_response)
#  File "/Library/Python/2.7/site-packages/onedrivesdk/collection_base.py", line 51, in _page_from_response
#    return response.collection_page
#  File "/Library/Python/2.7/site-packages/onedrivesdk/request/children_collection.py", line 148, in collection_page
#    self._collection_page = ChildrenCollectionPage(self._prop_dict["value"])
#KeyError: u'value'
```

**Comment by cdmayer** [comment]
What you have here looks pretty good. The error you're getting might not be specific to the Python SDK. I would recommend trying to do the same request using just the REST API over HTTP, just to make sure that you have a baseline. If you don't have Fiddler already, download [Fiddler](http://www.telerik.com/fiddler) and use the Composer to execute the same requests. Basically, you'll need to authenticate (you should be able to use the Python code you have here, then copy/paste `session.access_token` into the `Authentication: bearer` header), then do a GET /drive/root/children. See if that requests succeeds, and if the response you get is valid. If it is, we can dive deeper into the issue to see if it's Python-specific or not. Let me know if you get stuck with these instructions.

**Comment by jjbrink** [comment]
thank you for the quick reply -- you're right, it's failing at the API level too. it looks like an issue with converged authentication and onedrive for business APIs, will be digging more our end. thanks!
