### ISSUE TITLE
Need more detailed error on unexpected redirect_uri

### ISSUE THREAD

**Issue by ShaneC** [OneDrive/onedrive-sdk-python#29]
When executing the authentication sample code in /README.md, the following error is thrown when a redirect_uri is specified which doesn't contain a port:

`Traceback (most recent call last):
  File "C:\<FilePath>\Script.py", line 15, in <module>
    code = GetAuthCodeServer.get_auth_code(auth_url, redirect_uri)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\onedrivesdk\helpers\GetAuthCodeServer.py", line 51, in get_auth_code
    HOST, PORT = urlparse(redirect_uri).netloc.split(':')
ValueError: not enough values to unpack (expected 2, got 1)
Press any key to continue . . .`

For developers unfamiliar with OAuth in Python the reason for this isn't intuitive to derive. A check should be made early on to ensure the redirect_uri is valid for the scenario, and an exception should be raised to clearly indicate that.

**Comment by cdmayer** [comment]
Hey Shane, Thanks for leaving your comment. The docstring does have this outtake:
`redirect_uri (str): Redirect URI, as set for the app. Should be 
            something like "http://localhost:8080" for this to work.`

I went ahead and fixed it up in Master so that not providing a port defaults to port 80.
