### ISSUE TITLE
Request: Add example to upload large files to onedrive

### ISSUE THREAD

**Issue by vikasgupta1812** [OneDrive/onedrive-sdk-python#32]
Please add an example to upload large files to onedrive.

**Comment by cdmayer** [comment]
I have added large file support by default to Python 3.4+. Upgrade to the latest version using `pip install onedrivesdk`. You should be at version 1.0.7 or later.

By default, `upload_async()` will use a chunked upload scheme, uploading a few MB at a time. 

``` python
client.item(drive="me", path="foo/bar/baz.txt").upload_async("/path_to_file/baz.txt")
```

Let me know if this leaves you with any questions.
