### ISSUE TITLE
Does not allow to authenticate business accounts

### ISSUE THREAD

**Issue by dmasson** [OneDrive/onedrive-sdk-python#33]
By using the authentication example, I'm able to authenticate/authorize the client using personal account credentials, but, using business credentials, I get from the auth page a message saying that the account doesn't exist, therefore I cant authorize the client. 

The use case that I need to implement is for business accounts

**Comment by cdmayer** [comment]
Check out this other issue regarding the same: https://github.com/OneDrive/onedrive-sdk-python/issues/16

**Comment by dmasson** [comment]
Thank you !
