### ISSUE TITLE
Add support for query parameters (expand, filter, sort, etc.)

### ISSUE THREAD

**Issue by NotaLabs** [OneDrive/onedrive-sdk-python#37]
I was wondering how i could use the parameters listed [here](https://dev.onedrive.com/odata/optional-query-parameters.htm), when requesting child items.
I can`t seem to get the syntax right, when trying to get the results sorted by "lastmodifieddateTime".
Example source code would be appreciated.

`collection = client.item(drive="me", id="5A49630B8FC52EAA!109").children.request( >> ? <<).get()`

**Comment by cdmayer** [comment]
The reason you can't get it right is because that's not currently supported. Sorry! That's on the list of things to do next.

If you would like I can detail a general approach for writing your own `RequestBuilder` to accomplish this if you think you will need it.

**Comment by NotaLabs** [comment]
Thank for your fast answer.
It would be great if you could indicate this fact somewhere, so everyone would know that this feature is not yet avaible.

And thanks for offering help, but i think i will look into the REST API and then try to create a python programm for my purposes on my own.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
