### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by diman82** [OneDrive/onedrive-sdk-python#38]
Hi,

I get the following error message:
https://login.live.com/err.srf?lc=1033#error=unauthorized_client&error_description=The+client+does+not+exist.+If+you+are+the+application+developer%2c+configure+a+new+application+through+the+application+management+site+at+https://manage.dev.live.com/.

This is my configuration in https://apps.dev.microsoft.com 
![onedrive_auth_problem](https://cloud.githubusercontent.com/assets/17273166/16434425/5a0bb23e-3d98-11e6-990c-e776eb4d5327.jpg)

What could be the problem?

**Comment by cdmayer** [comment]
Can you show the code you're using to get this error? Make sure to remove client secret information.

**Comment by diman82** [comment]
import onedrivesdk
from onedrivesdk.helpers import GetAuthCodeServer

redirect_uri = "http://localhost:8080/"
client_secret = "[redacted]"

client = onedrivesdk.get_default_client(client_id='your_client_id',
                                        scopes=['wl.signin',
                                                'wl.offline_access',
                                                'onedrive.readwrite'])

auth_url = client.auth_provider.get_auth_url(redirect_uri)

#this will block until we have the code
code = GetAuthCodeServer.get_auth_code(auth_url, redirect_uri)

client.auth_provider.authenticate(code, redirect_uri, client_secret)

**Comment by cdmayer** [comment]
In this line:

``` python

client = onedrivesdk.get_default_client(client_id='your_client_id',
scopes=['wl.signin',
'wl.offline_access',
'onedrive.readwrite'])
```

you need to replace the fake string `'your_client_id'` with your actual client ID. Try this:

``` python
client = onedrivesdk.get_default_client(client_id='0000000044194611',
scopes=['wl.signin',
'wl.offline_access',
'onedrive.readwrite'])
```

Additionally, your `redirect_uri`s do not match. You need to either update the RedirectURI on your app registration page (the page you screenshot), or you need to update the `redirect_uri` variable to match what's on your app registration page.
