### ISSUE TITLE
bug in uploading

### ISSUE THREAD

**Issue by raingo** [OneDrive/onedrive-sdk-python#4]
In the line: https://github.com/OneDrive/onedrive-sdk-python/blob/master/src/python2/request/item_request_builder.py#L106

the `put` function should be `upload`, otherwise the uploading would fail on the example
`returned_item = client.item(drive="me", id="root").children["newfile.txt"].upload("./path_to_file.txt")`

**Comment by aclev** [comment]
Hey @raingo Thanks for finding the bug! I'll look into getting it fixed.
