### ISSUE TITLE
Authentication Problem

### ISSUE THREAD

**Issue by ksp1717** [OneDrive/onedrive-sdk-python#40]
HI
I am trying to build a onedrive ubuntu app using python sdk, but the authentication process is giving me some problems.
I am trying to run the example CommandLineFileExplorer.py script with my own client_id and client_secret.

I registered my app and used the application_id for 'client_id' and password for 'client_secret'. When I try to get the code by authentication, I only get a message saying 'Microsoft is unable to complete this request'.

Any help regarding this is appreciated.

Thanks

**Comment by kaifeng-h** [comment]
Redirect URL should also be added in your own app. Did you miss this option in your app config?

**Comment by ksp1717** [comment]
This is what I have in my app code. I have also attached the app registration page from microsoft app dev page.
![screenshot from 2016-07-17 21-17-00](https://cloud.githubusercontent.com/assets/16392966/16904953/749224e6-4c64-11e6-9be1-99e3dd23d87d.png)

`#code starts here

```
redirect_uri = "http://localhost:8080/" 

client_secret = "password from the app registration"

# changed client_id to my client id.

client = onedrivesdk.get_default_client(client_id='app id from the app registration',
                                        scopes=['wl.signin',
                                                'wl.offline_access',
                                                'onedrive.readwrite'])

auth_url = client.auth_provider.get_auth_url(redirect_uri)

# Block thread until we have the code
code = GetAuthCodeServer.get_auth_code(auth_url, redirect_uri)

# Finally, authenticate!
client.auth_provider.authenticate(code, redirect_uri, client_secret)`
```

**Comment by kaifeng-h** [comment]
click **add platform** button, add web platform and you should see a redirect uri option. By the way, I don't know the difference between My Application and Live SDK app. I guess both will work. If not, try applying a Live SDK App.

**Comment by ksp1717** [comment]
Thanks you MiniYellow. Adding the platform fixed it.

Also I checked LiveSDK app and it lead me to the same My Application. I think microsoft has integrated multiple things into one authentication system.
