### ISSUE TITLE
Authentication without needing a web browser

### ISSUE THREAD

**Issue by diman82** [OneDrive/onedrive-sdk-python#41]
I'm running onedrive-sdk for python on an embedded device, and I get the following error message:

```
root@DD-WRT:/opt/bin# python3.5 onedrivesdk3.5.py
Traceback (most recent call last):
  File "onedrivesdk3.5.py", line 16, in <module>
    code = GetAuthCodeServer.get_auth_code(auth_url, redirect_uri)
  File "/opt/lib/python3.5/site-packages/onedrivesdk/helpers/GetAuthCodeServer.py", line 60, in get_auth_code
    s = GetAuthCodeServer((host_address, port), code_acquired, GetAuthCodeRequestHandler)
  File "/opt/lib/python3.5/site-packages/onedrivesdk/helpers/GetAuthCodeServer.py", line 76, in __init__
    HTTPServer.__init__(self, server_address, RequestHandlerClass)
  File "/opt/lib/python3.5/socketserver.py", line 443, in __init__
    self.server_bind()
  File "/opt/lib/python3.5/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/opt/lib/python3.5/socketserver.py", line 457, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```

That is after I've manually added 'webbrowser.py' to lib dir, otherwise I get a module not found exception.

If I get the code from a PC, by running the auth process provided in an example, I get the following error:

```
root@DD-WRT:/opt/bin# python3.5 onedrivesdk3.5.py
Traceback (most recent call last):
  File "onedrivesdk3.5.py", line 20, in <module>
    client.auth_provider.authenticate(code, redirect_uri, client_secret)
  File "/opt/lib/python3.5/site-packages/onedrivesdk/auth_provider.py", line 169, in authenticate
    data=params)
  File "/opt/lib/python3.5/site-packages/onedrivesdk/http_provider.py", line 71, in send
    custom_response = HttpResponse(response.status_code, response.headers, response.text)
  File "/opt/lib/python3.5/site-packages/onedrivesdk/http_response.py", line 51, in __init__
    raise Exception(str(message["error"]))
Exception: invalid_grant
```

Please add support for manual auth (done on a PC) , like in python-onedrive project.

**Comment by cdmayer** [comment]
Actually there is already support for what you want! You can authenticate without the help of the `GetAuthCodeServer` class. Something like this:

``` python
import onedrivesdk

redirect_uri = 'http://localhost:8080/'
client_secret = 'your_client_secret'
client_id='your_client_id'
api_base_url='https://api.onedrive.com/v1.0/'
scopes=['wl.signin', 'wl.offline_access', 'onedrive.readwrite']

http_provider = onedrivesdk.HttpProvider()
auth_provider = onedrivesdk.AuthProvider(
    http_provider=http_provider,
    client_id=client_id,
    scopes=scopes)

client = onedrivesdk.OneDriveClient(api_base_url, auth_provider, http_provider)
auth_url = client.auth_provider.get_auth_url(redirect_uri)
# Ask for the code
print('Paste this URL into your browser, approve the app\'s access.')
print('Copy everything in the address bar after "code=", and paste it below.')
print(auth_url)
code = input('Paste code here: ')

client.auth_provider.authenticate(code, redirect_uri, client_secret)
```

That should do it without any dependencies... except of course that you need a browser, which segues into your first issue. Running on an embedded device is a bit more complicated because Microsoft Account OAuth requires clients to have Javascript available. The easiest way to accomplish that is usually a web browser, but of course Raspberry Pi and other embedded devices do not have that available. One possibility would be to use Selenium and Iceweasel to 'fake' a browser, such as in this [StackOverflow thread](http://stackoverflow.com/questions/25027385/using-selenium-on-raspberry-pi-headless). That's not done yet, but if you take such an approach definitely submit a pull request!

**Comment by diman82** [comment]
Confirm this solution/workaround works.

> That should do it without any dependencies... except of course that you need a browser, which segues into your first issue. Running on an embedded device is a bit more complicated because Microsoft Account OAuth requires clients to have Javascript available. The easiest way to accomplish that is usually a web browser, but of course Raspberry Pi and other embedded devices do not have that available. One possibility would be to use Selenium and Iceweasel to 'fake' a browser, such as in this StackOverflow thread. That's not done yet, but if you take such an approach definitely submit a pull request!

P.S Browser is not an issue (even though I'm working on an embedded device - ARM7 router), since I'm under the same WAN IP for both my embedded device and a PC, so I simply copy paste between PC & SSH terminal, but thanks for the reference anyway.

**Comment by cdmayer** [comment]
Glad to hear that worked for you. I'm going to close the issue - please reopen if you have any other problems.

**Comment by diman82** [comment]
Just one more quick question:
Is it possible, to (auto) export a refresh token, so that the SDK will auto find it (or manually load it upon run) to skip the auth process for each & every run? I think this feature existed in the old API..

**Comment by cdmayer** [comment]
Yes, that's what the [Session](https://github.com/OneDrive/onedrive-sdk-python/blob/master/src/onedrivesdk/session.py) object is for. The implementation in the SDK is really a demonstration, and not very secure (basically stores everything in plain text). It's recommended that you implement the `SessionBase` class with a more secure scheme. Anyhow, once you've done that, the pattern is easy.

``` python
# When creating your AuthProvider
auth_provider = onedrivesdk.AuthProvider(
    http_provider=http_provider,
    client_id=client_id,
    scopes=scopes,
    session_type=YourSessionClass)

# Do your authentication above
client.auth_provider.save_session(your_args)

# Next time you start up, check for an existing session. If one is found,
client.auth_provider.load_session(your_args)
client.auth_provider.refresh_token()
```

Hope that helps.

**Comment by diman82** [comment]
Yes it works.
Thanks for 'plain text' warning!
You may close the issue.

**Comment by RaspiRepo** [comment]
Hi diman82

I had same issue with getting One drive access token from Raspberry PI without browser or UI/Monitor.   You dont need to copy & Paste access toekn from any other system or browser. Check out following link

https://github.com/RaspiRepo/Pi_OneDrive

On the python script you need to replace your Onedrive user name/password and client ID/secret from Microsoft application control panel by adding your application.

This method is bit cracking approach. But once you get access token that can be used for long time by setting up refresh request.

**Comment by cdmayer** [comment]
Just a note about that code: it bypasses the acceptance form from Microsoft Account. That means that the app can ask for ANY permissions to your account and you are accepting them. If you choose to use this code for a small side project that's one thing, but please do NOT use this code for a product or app that will be distributed to other users.

**Comment by jpkey** [comment]
Hi, 
I am also trying to authenticate using your snippet above. 

I am receiving an error after pasting the code into my terminal: 
`client.auth_provider.authenticate(code, redirect_uri, client_secret)
  File "/usr/local/lib/python3.5/dist-packages/onedrivesdk/auth_provider.py", line 203, in authenticate
    data=params)
  File "/usr/local/lib/python3.5/dist-packages/onedrivesdk/http_provider.py", line 71, in send
    custom_response = HttpResponse(response.status_code, response.headers, response.text)
  File "/usr/local/lib/python3.5/dist-packages/onedrivesdk/http_response.py", line 51, in __init__
    raise Exception(str(message["error"]))
Exception: invalid_request
`

Any ideas how to fix this? Thanks.

**Comment by cdmayer** [comment]
Can you show your code please?

**Comment by prakashpandey** [comment]
Why is this issue closed?
As per the issue heading `Authentication without needing a web browser?`, all answer I see hear required browser interaction(other than some solution using selenium). 

Do we have anyway in which we can authenticate without using browser also not using selenium?

**Comment by jpatel3** [comment]
What if I have `accesstoken`, I think there should be a way to use that to make required call to api?  

I am using [onedrive picker](https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/?view=odsp-graph-online) code to get file details and `accesstoken` and would like to request the file download from python backend. While following the code provided in the readme, it thorws `Address already in use` error.
