### ISSUE TITLE
Authentication on non-GUI system (no web browser)

### ISSUE THREAD

**Issue by clarktlaugh** [OneDrive/onedrive-sdk-python#43]
I saw issue #8 regarding a workaround for authentication that requires running a script on another system first.

I, too, am experiencing the same problem.  I have a Linux system with no GUI -- only links / w3m installed, and Microsoft login is failing because my browser doesn't support Javascript.

Would doing something similar to what Google's python API / oauth2client (https://github.com/google/oauth2client) does be possible?

(Applicable code here: https://github.com/google/oauth2client/blob/master/oauth2client/tools.py)

I use their python client and the authentication process is very simple when you don't have a local browser.

When you run your script the first time, you pass a "--noauth_local_webserver" parameter on the command line which causes their client to genereate a URL that you then go to on another system that does have a web browser.  The script then blocks waiting on you to login.  Once you login on your other system, the script saves off the credentials and moves on.

All subsequent times that you run your script, you don't have to specify the extra command line option.  The credentials are loaded and used, and your script works just fine.

This type of flow is very simple on the end user and doesn't require having additional special setup (other than access to some device -- even a smart phone -- with a web browser).

**Comment by cdmayer** [comment]
Almost your exact question was answered recently in #41. Please let me know if that leaves you with any other questions!

**Comment by clarktlaugh** [comment]
I haven't made a very polished fix yet, but by changing just a few lines in GetAuthCodeServer.py, I can get the same basic behavior to work:

Instead of opening a web browser, display the URL that the user needs to browse to, then prompt for the code to be entered:

```
#webbrowser.open(auth_url)
print "Browse here: {0}".format(auth_url)
code = raw_input('Enter verification code: ').strip()
```

Don't wait here, as the raw_input() call blocks:

```
# At this point the browser will open and the code
# will be extracted by the server
#code_acquired.wait()  # First wait for the response from the auth server
#code = s.auth_code
```

**Comment by clarktlaugh** [comment]
Sorry - I saw your comment after I posted my last comment.  I'll take a look.

**Comment by clarktlaugh** [comment]
I'll try, but I think that will work -- thank you
