### ISSUE TITLE
Question: How do I interact with (get contents, upload to, etc) a shared folder?

### ISSUE THREAD

**Issue by clarktlaugh** [OneDrive/onedrive-sdk-python#44]
I can call client.item(id="root").children.get() to get the contents of my drive, which includes folders that have been shared with me.  When I try to enumerate the contents of that shared folder, it has no children.  What is the correct way to access a shared folder?

**Comment by grishbhasin** [comment]
I am also not able to access shared folder what the correct way of doing it.
