### ISSUE TITLE
Setter and getter on datetime properties are inconsistent

### ISSUE THREAD

**Issue by clarktlaugh** [OneDrive/onedrive-sdk-python#45]
I have some code where I am trying to modify the last_modified_time on item.file_system_info so I can preserve the timestamp of the original data I'm uploading.

The problem can be demonstrated without even uploading the file:

I'm using the following code to create the Item I was going to use to patch the uploaded file with:
   fsi = onedrivesdk.FileSystemInfo()
   fsi.last_modified_date_time = dt    # dt is initialized by datetime.fromtimestamp()
   fsi.created_date_time = dt
   i = onedrivesdk.Item()
   i.id = item.id
   i.file_system_info = fsi

Immediately doing the following results in an error:

   print fsi.last_modified_date_time

.
.
.
File "/home/clarkl/.local/lib/python2.7/site-packages/onedrivesdk/model/file_system_info.py", line 62, in last_modified_date_time
    return datetime.strptime(self._prop_dict["lastModifiedDateTime"].replace("Z", ""), "%Y-%m-%dT%H:%M:%S.%f")
  File "/usr/lib/python2.7/_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data '2013-10-11T15:31:03' does not match format '%Y-%m-%dT%H:%M:%S.%f'

The problem is that the setter function for the dates in file_system_info use .isoformat() which, if microseconds is 0, does not include that component in the time string (i.e. no .000000).  But, the getter function expects it to be there with the ".%f" in the format string.

**Comment by cdmayer** [comment]
Actually, modifying `last_modified_time` is not possible. You can see it's read-only in the API docs: https://dev.onedrive.com/resources/item.htm.

Still, this is a bug for other datetime operations.

**Comment by clarktlaugh** [comment]
I saw a post / article somewhere that said it was possible now.  I read it yesterday -- I'll try to post a link when I find it.

The API does seem to allow an update.

I can verify by doing pprint(vars(item)) on the return of client.item().update(patch).

The OneDrive web UI also reflects that value in the "Modified" field of the properties pane (though it still seems to show "Date created" as the upload date, which is extremely annoying.

**Comment by clarktlaugh** [comment]
I just read your response again.  I'm not modifying item.last_modified_date_time.  I'm modifying item.file_system_info.last_modified_date_time (https://dev.onedrive.com/facets/filesysteminfo_facet.htm)

**Comment by cdmayer** [comment]
I think this was fixed in this branch but the branch was never pushed (sorry!). @D4N14L can you verify? https://github.com/OneDrive/onedrive-sdk-python/tree/datetime-fixes

**Comment by clarktlaugh** [comment]
I'm currently only using the version installed via pip.  Is it safe to just grab the files from that commit and overwrite what I already have installed.  Or, is there a better way to test this branch?

**Comment by D4N14L** [comment]
@cdmayer does not look like it was fixed, will work on that
@clarktlaugh while you should be able to do that, I wouldn't recommend that since we will be pushing out a new version to pip very soon after fixing. Additionally, this branch is not going to fix your issue, so it would be work for nothing. We'll have this fixed soon!

**Comment by cdmayer** [comment]
Fix deployed in 1.1.2
