### ISSUE TITLE
Question: How does this project relate to https://github.com/microsoftgraph/msgraph-sdk-python?

### ISSUE THREAD

**Issue by clarktlaugh** [OneDrive/onedrive-sdk-python#46]
I just came across the set of projects under https://github.com/microsoftgraph and see what looks to be a very similar Python SDK.  Should I be using one over the other?  Are they kept in sync?

Thank you,
Clark

**Comment by cdmayer** [comment]
The Graph API is a different API than the OneDrive API. Graph provides access to many different resources that can be accessed within Microsoft, such as an Outlook inbox, in addition to OneDrive resources. Essentially, you should use Graph unless there is something supported in the OneDrive SDK that is not supported in the Graph SDK (for example, if you want to authenticate to SharePoint On Prem, which is not compatible with Graph authentication).

**Comment by clarktlaugh** [comment]
Are the two projects kept in sync?  My concern is that, looking at the code, issue #45 here also seems to be present in the the Graph API as well.  Do I need to open an issue there, or do changes here get made there as well?

**Comment by cdmayer** [comment]
They are generated from the same templates, so when that issue is fixed in one, it will also be fixed in the other. However, the release cadences are a bit different so the fixes may not get released quite at the same time.
