### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by paul-oprea** [OneDrive/onedrive-sdk-python#51]
Hello,

I am getting

> requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', error(32, 'Broken pipe'))

early on when trying to upload a large file (>4GB).
I have successfully uploaded small files using the example provided 
`returned_item = client.item(drive='me', id='root').children['newfile.txt'].upload('./path_to_file.txt')`
(so app declared, went through the initial drill etc etc), but fails for larger ones.

Please advise.

Kind regards
Paul

**Comment by cdmayer** [comment]
Files >100MB must be uploaded using an upload session. You should be able to change just a couple things:
1. Make sure you are using Python3, as async is not supported in the Python2 version of the library.
2. Change `.upload` to `.upload_async`. This will automatically manage creating a session, uploading the file in chunks, and closing the session.

Here's an example:

``` python
client.item(drive="me", path="foo/bar.txt").upload_async("./bar.txt")
```
