### ISSUE TITLE
url quote in children collection url build

### ISSUE THREAD

**Issue by ghost** [OneDrive/onedrive-sdk-python#53]
Hello,

I use the following code to upload a file which filename is "a + b.txt".
But the uploaded file's name was changed to "a   b.txt".

`client.item(drive='me', id='root').children['a + b.txt'].upload('./path_to_file.txt')`

I trace the source code, found the url build method does not quote the filename.

```
class RequestBuilderBase(object):  
  def append_to_request_url(self, url_ssegment):  
     return self._request_url + "/" + url_segment  
```

so i changed my code to:
`client.item(drive='me', id='root').children[urllib.quote('a + b.txt')].upload('./path_to_file.txt')`

then the uploaded file's name is correct.

Is this a bug?
Or I should quote the file name for the _**children[]**_ collection?

Kind regards
Frank

**Comment by cdmayer** [comment]
Before the request is sent it gets url encoded. You are seeing the result of that. Similarly if your name were `a %21 b.txt` you would get `a ! b.txt`. This behavior is expected. Keep using the `quote` method.
