### ISSUE TITLE
Allow using the client without the authorization flow of the SDK

### ISSUE THREAD

**Issue by denniseffing** [OneDrive/onedrive-sdk-python#54]
I use my own OAuth client for authorization with the implicit flow and I successfully retrieved the access token etc. from OneDrive. 
The SDK however doesn't allow me to create an authenticated OneDriveClient object with my already obtained access token. Is there any way around this? I really want to avoid the work needed for implementing my own client based on the REST API.

**Comment by D4N14L** [comment]
Yes there is a way around this!

If you would like to use a token that you obtained on your own, you will need to construct the OneDriveClient as per usual, but pass in a `Session` object, like this:

```
http_provider = onedrivesdk.HttpProvider()
auth_provider = onedrivesdk.AuthProvider(
    http_provider=http_provider,
    client_id=client_id,
    scopes=scopes)

session = onedrivesdk.Session(
    token_type,                  #in token response
    expires_in,                  #in token response
    scope,                       #in token response
    access_token,                #in token response
    client_id,
    auth_token_url,              #can be None for you, since you're handling auth
    redirect_uri,                #can be None for you, since you're handling auth
    refresh_token,               #in token response, if you asked for one, otherwise None
    client_secret)               #if you have one, otherwise None

auth_provider._session = session
client = onedrivesdk.OneDriveClient(api_base_url, auth_provider, http_provider)
```

Keep in mind that this means that if the token is expired, the AuthProvider will attempt to refresh the token using the refresh_token, so it must be provided in this case. If it is not, it will raise a `RuntimeError`.

**Comment by D4N14L** [comment]
Another thought, if you want to avoid all the scaryness that comes from just throwing a `Session` object in, is to implement all of your authentication flow in an object based on [AuthProviderBase](https://github.com/OneDrive/onedrive-sdk-python/blob/master/src/onedrivesdk/auth_provider_base.py). This is what we based [AuthProvider](https://github.com/OneDrive/onedrive-sdk-python/blob/master/src/onedrivesdk/auth_provider.py) on and makes it super flexible for you to implement yourself.

**Comment by denniseffing** [comment]
Thank you very much for the fast answer, the session object looks promising. I will have to see what I do about the missing refresh token and the resulting error handling. The implicit flow doesn't provide one and then again, I couldn't use it anyways since I'm not using my client secret (open source application, no way to keep the client secret confidential).
And yes, I already noticed the AuthProviderBase but I couldn't find any documentation for any method and their return values, so I wasn't sure if that would help me or how that would help me exactly.
I may look further into the base class soon.

**Comment by D4N14L** [comment]
If you're looking to get a refresh token, you just need to add the `offline_access` scope.

I would recommend looking at AuthProvider for a good example of what AuthProviderBase should do or how to implement/what to return. There are fully-fleshed-out comments there with everything you would need to make your own implementation.

**Comment by denniseffing** [comment]
Short update: My own implementation works fine but it's a shame that you can't retrieve a refresh token when using the token flow (even when adding offline_access to the scopelist). This makes maintaining desktop applications pretty difficult and the usage is quite inconvenient for the user.
See https://dev.onedrive.com/auth/msa_oauth.htm.

Thanks for you help @D4N14L.

**Comment by remort** [comment]
Now import it like that: `from onedrivesdk.session import Session`.
