### ISSUE TITLE
Refactor json encoding and decoding

### ISSUE THREAD

**Issue by cdmayer** [OneDrive/onedrive-sdk-python#59]
JSON values are getting serialized and deserialized in-line. This makes it difficult to catch problems with invalid JSON (such as a response with an empty body, or with a body that is invalid JSON). Refactor the generated code to wrap the serialization/deserialization process and return proper OneDriveErrors when an invalid value is returned.

**Comment by rschork** [comment]
Bump - I have been getting JSON errors a lot recently. Things like the below:

onedrivesdk.error.OneDriveError: malformed - The following invalid JSON was returned:
<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'
><html xmlns='http://www.w3.org/1999/xhtml'><head><meta content='text/html; charset=utf-8' http-equiv='content-type'/><s
tyle type='text/css'>body {font-family:Arial; margin-left:40px; }img  { border:0 none; }#content { margin-left: auto; ma
rgin-right: auto }#message h2 { font-size: 20px; font-weight: normal; color: #000000; margin: 34px 0px 0px 0px }#message
 p  { font-size: 13px; color: #000000; margin: 7px 0px 0px0px}#errorref { font-size: 11px; color: #737373; margin-top: 4
1px }</style><title>OneDrive</title></head><body><div id='content'><div id='message'><h2>Our services aren't available r
ight now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p></div><div id='err
orref'><span>Ref A: 106DA54BC29E4340B334EDE899669B52 Ref B: AMS04EDGE0417 Ref C: 2018-04-30T19:57:06Z</span></div></div>
</body></html>

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
