### ISSUE TITLE
Error when expanding thumbnails in get Item request 

### ISSUE THREAD

**Issue by Nyshiki** [OneDrive/onedrive-sdk-python#63]
Hi, 
I'm getting an ImportError when I try to get a Item with expanded thumbnails field.
Here's the code to reproduce it:
`returned_item = client.item(drive='me', id='file_id').request(expand="thumbnails").get()`

I would like to obtain the Item and thumbnails information in a single request and this seems the right way to do it.
BTW I cloned the repo and patched the code adding the missing import statement and got the function to work, am I missing something?
I use python 2.7, onedrivesdk 1.1.4 .

Thank you

**Comment by D4N14L** [comment]
Hey! Just wanted to let you know that we are looking into this. While your case does only involve that fix, and will work for you, there were a few other related issues uncovered while looking into it.

**Comment by D4N14L** [comment]
This is fixed with #65. Keep in mind that paging has now changed for collections, See the README for an example on how to do this now.
