### ISSUE TITLE
Malformed auth_url returned

### ISSUE THREAD

**Issue by ybizeul** [OneDrive/onedrive-sdk-python#70]
Here is a sample of an URL returned by auth.get_auth_url (as in the sample code) :

```
u"('https://login.microsoftonline.com/common/oauth2/authorize',)?redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&response_type=code&client_id=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
```

Because of that, the auth window doesn't open

**Comment by cdmayer** [comment]
Did you [change](https://github.com/OneDrive/onedrive-sdk-python/blob/master/src/onedrivesdk/auth_provider.py#L39) `MSA_AUTH_SERVER_URL`? It seems like you are mixing unicode strings in with regular strings, which is why you're seeing this issue.

**Comment by ybizeul** [comment]
It looks like it indeed, but I didn't change that part of the code:

```
auth_server_url='https://login.microsoftonline.com/common/oauth2/authorize',
```

I even checked the script file itself see if there was weird encoded visible but couldn't spot anything weird :

```
00000190  6f 72 69 7a 65 27 2c 0a  61 75 74 68 5f 74 6f 6b  |orize',.auth_tok|
000001a0  65 6e 5f 75 72 6c 3d 27  68 74 74 70 73 3a 2f 2f  |en_url='https://|
000001b0  6c 6f 67 69 6e 2e 6d 69  63 72 6f 73 6f 66 74 6f  |login.microsofto|
000001c0  6e 6c 69 6e 65 2e 63 6f  6d 2f 63 6f 6d 6d 6f 6e  |nline.com/common|
000001d0  2f 6f 61 75 74 68 32 2f  74 6f 6b 65 6e 27 0a 0a  |/oauth2/token'..|
000001e0  68 74 74 70 20 3d 20 6f  6e 65 64 72 69 76 65 73  |http = onedrives|
```

Here is my line in the file you mentioned, it's the same :

```
    MSA_AUTH_SERVER_URL = "https://login.live.com/oauth20_authorize.srf"
```

**Comment by ybizeul** [comment]
Oh boy...

If you look that line, for some reason there is a comma in the end that shouldn't be here.

Now it opens the window just fine but complains about resource not returned, but I suspect that's something I have to check with my company, I don't have admin access to onedrive and I don't know what is published.

```
Traceback (most recent call last):
  File "corporate.py", line 21, in <module>
    auth.authenticate(code, redirect_uri, client_secret, resource=resource)
NameError: name 'resource' is not defined
```

The request only returned `code` and `session_state` parameters.

**Comment by cdmayer** [comment]
Your issue should (hopefully) be obvious: when you have a trailing comma, you create a tuple with a single member. When the library called `format` it actually called in on the tuple, so you got the string representation of the tuple: `({url},)`.

The error you are getting now just means that you haven't created the variable `resource` yet. You should have used the Discover Service to help you retrieve the resource. It could be something like this: `https://contoso-my.sharepoint.com/`.

**Comment by ybizeul** [comment]
Pull #71 created for the original issue

**Comment by ybizeul** [comment]
You mean the comma wasn't a typo in the example?

**Comment by cdmayer** [comment]
Many apologies! I misunderstood your comment; yes, that was an issue with the sample. I merged your PR. Thank you for pointing it out.
