### ISSUE TITLE
The Borg: All instantiated objects carry the same state

### ISSUE THREAD

**Issue by dtheodor** [OneDrive/onedrive-sdk-python#78]
```python
>>> from onedrivesdk import *
>>> i = Item()
>>> i.name = 'a name'
>>> i2 = Item()
>>> i2.name
'a name'
>>> i2.name = 'hi there'
>>> i.name
'hi there'
```

*All* instances share the exact same attributes. The reason for that is this constructor, which is recurring among all models

```python
class Item(OneDriveObjectBase):

    def __init__(self, prop_dict={}):
        self._prop_dict = prop_dict
```
The default parameter `{}` is evaluated once when the function definition is executed, resulting in all instances sharing the same single `_prop_dict` dictionary object (explained at https://docs.python.org/3/reference/compound_stmts.html#function-definitions). Combined with the fact that all attributes accesses are done through property setters/getters that modify this dictionary, we end up with a re-imagining of the [Borg pattern](http://code.activestate.com/recipes/66531-singleton-we-dont-need-no-stinkin-singleton-the-bo/)

**Comment by D4N14L** [comment]
You are correct. Will look into getting this one fixed. Thanks for reporting!
