### ISSUE TITLE
Accessing and Writing to Files In One Drive

### ISSUE THREAD

**Issue by ProLuck** [OneDrive/onedrive-sdk-python#82]
Hi There,

I want to be able to read / write to files stored on 'one drive for business' which is due to be rolled out for our business.
 
However, the process seems a little complex to me. Microsoft site states that there is no SDK available for 'One drive for Business' is this correct. 

Is any one here able to point me the right steps for achieving this?

**Comment by cdmayer** [comment]
Check out our documentation: https://github.com/OneDrive/onedrive-sdk-python#onedrive-for-business

Long story short: you can use the same code to access your OneDrive for Business files as you would to access OneDrive. The only differences are in authentication and construction of the `OneDriveClient`

**Comment by ProLuck** [comment]
thanks @cdmayer 
does this still involve me registering my app with Azure active dir etc then mapping it with my office 365 account...? 
also, when specifying my resource in the code shown by you, should that be based on a Sharepoint site instead of direct line to office 365?

**Comment by cdmayer** [comment]
Yes it does. You (or your administrator) would need to register you app before it can be used with your tenant.

Not sure what you mean. Can you give examples of each?

**Comment by ProLuck** [comment]
So once they register the app and provide me with the client secret and key they will have to link this to my account? As initially i want to use the client secret provided by them to update stuff under my one drive? is that feasible? 

for part2 of the question? Online it also talks about having a developer site which is then configured under the code? am i to set my resource based on the site created for me example: resource='https://xxxxxxx-my.sharepoint.com/'

**Comment by cdmayer** [comment]
Your admin will only need to approve the app. After that, when you use the OneDrive SDK to access your OneDrive, you'll get a consent window that will ask, "This app wants to access your OneDrive. Is that OK?" Going through that consent flow will grant the app access to your OneDrive. No need for your admin to manually consent your account.

Yes, you would point it to the resource you provided. You can use Resource Discovery to see what resources your app can access, too. You can see more information about how to do that here: https://github.com/OneDrive/onedrive-sdk-python#onedrive-for-business

**Comment by ProLuck** [comment]
Thanks...I will give it a try..

**Comment by ProLuck** [comment]
@cdmayer does it have to developer sharepoint site e.g...can I not point it directly to one drive?

**Comment by cdmayer** [comment]
When you construct the client object, you pass in a resource (your SharePoint instance). Then, when you authenticate, you will log in with a user, which implicitly points the client at that user's drive.

**Comment by ProLuck** [comment]
thanks @cdmayer  got it working.
