### ISSUE TITLE
Upload sockets left open with FIN_WAIT

### ISSUE THREAD

**Issue by ybizeul** [OneDrive/onedrive-sdk-python#83]
Looking at sockets used by the big file upload I noticed sockets left open in `FinWait2` state.

Every single socket used to upload the 10m pieces. After some research, I saw this documentation :

https://kb.iu.edu/d/ajmi

Is it possible onedrive-sdk-python code doesn't cleanly close the socket?

```
[...]
   tcp4 10.0.1.136:58718<->a-0011.a-msedge.net:443                                          en0      FinWait2        6026 B            10 MiB     0 B       0 B
   tcp4 10.0.1.136:58727<->a-0011.a-msedge.net:443                                          en0      FinWait2        6026 B            10 MiB     0 B       0 B
   tcp4 10.0.1.136:58739<->a-0011.a-msedge.net:443                                          en0      FinWait2        6026 B            10 MiB     0 B       0 B
```

**Comment by D4N14L** [comment]
The SDK code uses the requests library to accomplish the task of posting the slices in the fragment_upload_async method. The only time I can think of this happening is when there is an error in the connection and the socket wasn't closed properly, however you seem to be indicating that this occurs on each session? If I could get more info from you on that, it would really help. Thanks!

**Comment by ybizeul** [comment]
Yes, every single session ends up in FinWait2. Probably not a big deal I guess, I found that during other investigations. I'd be glad to collect any useful information

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
