### ISSUE TITLE
Add support for recursive upload

### ISSUE THREAD

**Issue by diman82** [OneDrive/onedrive-sdk-python#87]
Can you please add support for recursive upload (folder/subfolder1|subfolder2/file1|file2)?
I understand that this is more of a client implementation functionality, but I'm positively sure it is a demanded feature..

**Comment by diman82** [comment]
I've managed to get it working by my own, sharing my script, if anyone will need this:
https://gist.github.com/diman82/d0db6a970bb4d9949fcdb680dd184ef5

I'm using a slightly modified version of:
https://github.com/RaspiRepo/Pi_OneDrive  for auth:
https://gist.github.com/diman82/101c9928cf3425bc05a40de5277b7ea1

**Comment by D4N14L** [comment]
I'm going to close this out. Recursive upload as you say is definitely a client implementation. Though, I'm glad to see you could make it work rather easily with the SDK! If you would like to implement some form of extension into the SDK to do something like this, feel free to write an implementation under the `/src/onedrivesdk/extensions` directory, likely extending from `ItemRequestBuilder`, and create a pull request.

**Comment by diman82** [comment]
Could you please provide an short example of an extension impl.? It's not so clear to me.
Basically, I've created a function (please don't pay attention to content) in a new python file ('one_drive_client_item_helper' under the extensions dir):

`def upload_recursive(self, client, path):
    """Uploads the file using PUT

    Args:
        path (str):
            The path to the local file to upload.

    Returns:
        :class:`Item<onedrivesdk.model.item.Item>`:
            The created Item.
    """
    self.method = "PUT"
    entity_response = self.send(path=path)
    entity = Item(json.loads(entity_response.content))

    foldermappingdict = {}
    for name in os.listdir(path):
        global current_folder_id
        currentpath = os.path.join(path, name)
        if os.path.isfile(currentpath):
            relative_path_to_upload = os.path.relpath(currentpath, PATH_TO_LOCAL_UL).replace('\\', '/')    # change the path to *nix platform style
            client.item(drive="me", path=(PATH_TO_REMOTE_UL+relative_path_to_upload).replace('\\', '/')).upload(currentpath.replace('\\', '/'))
        elif os.path.isdir(currentpath):
            try:
                f = onedrivesdk.Folder()
                i = onedrivesdk.Item()
                i.name = name
                i.folder = f

                returned_item = client.item(drive='me', id=current_folder_id).children.add(i)
                foldermappingdict[currentpath] = current_folder_id   # map current folder path to cloud folder_id
                current_folder_id = returned_item._prop_dict['id']
            # ignore "directory already exists"
            except Exception as e:
                print(e)

            upload_recursive(client, currentpath)
            current_folder_id = foldermappingdict[currentpath]    # reference back to initial current_folder_id to continue create directories in cloud in the proper place

    return entity`

And added `OneDriveClient.upload_recursive = upload_recursive` at the bottom of file, but I can't get this function discovered when running something like: `client.item.upload_recursive(client, path=path_to_ul)`

This is a debug error message:
 {AttributeError}'function' object has no attribute 'upload_recursive'

Can you please advise what I'm doing wrong?

On Dec 17, 2016 1:33 AM, "Daniel Nadeau" <notifications@github.com> wrote:

I'm going to close this out. Recursive upload as you say is definitely a
client implementation. Though, I'm glad to see you could make it work
rather easily with the SDK! If you would like to implement some form of
extension into the SDK to do something like this, feel free to write an
implementation under the /src/onedrivesdk/extensions directory, likely
extending from ItemRequestBuilder, and create a pull request.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/OneDrive/onedrive-sdk-python/issues/87#issuecomment-267721735>,
or mute the thread
