### ISSUE TITLE
Size field mismatch size of content downloaded

### ISSUE THREAD

**Issue by xybu** [OneDrive/onedrive-sdk-python#88]
I noticed that for some (not all) files in my OneDrive Personal account the size reported by the API is not consistent with the length of content actually downloaded, yet the SHA-1 hash values match.

For example, I have a JPEG file named `IMG_0100.JPG` whose `size` is 62671 bytes reported by API yet the downloaded file is only 57814 bytes. However, the API says the SHA-1 hash is `D4AE13DB398E5F51A1DCA6908212B2EF855AB04C` which matches the SHA-1 hash of the downloaded file. Because the hashes match, I think the file is downloaded properly and thus the file size reported by the OS is correct.

Follow-ups:
* I re-uploaded the downloaded file back to OneDrive yet value of size field of the returned Item does not change.
* Most such files seem MSOffice, PDF, or image files. But I don't have various types of files in my OneDrive.

Any idea why this happened?

I'm running Ubuntu 16.04 64-bit and using Python 3.5.

Cross-reference: https://github.com/OneDrive/onedrive-api-docs/issues/492

**Comment by D4N14L** [comment]
I'm going to close here. I believe this is a service level issue. If you think this is wrong, feel free to reopen!
