### ISSUE TITLE
Selenium/PhantomJS error: Unable to find element with name

### ISSUE THREAD

**Issue by diman82** [OneDrive/onedrive-sdk-python#91]
I get the following error message when using the PhantomJS driver of Selenium:

`c:\Python36\Scripts>..\python.exe onedrive_ul.py
Traceback (most recent call last):
  File "onedrive_ul.py", line 26, in <module>
    code = onedrive_auth.get_auth_code()
  File "c:\Python36\Scripts\onedrive_auth.py", line 34, in get_auth_code
    element = driver.find_element_by_name('ucaccept')
  File "c:\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 365, in find_element_by_name
    return self.find_element(by=By.NAME, value=name)
  File "c:\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "c:\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "c:\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: {"errorMessage":"Unable to find element with name 'ucaccept'","request":{"headers":{"Accept":"application/json","Accept-Encoding":"identity","Connection":"close","Content-Length":"91","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:3081","User-Agent":"Python-urllib/3.6"},"httpVersion":"1.1","method":"POST","post":"{\"using\": \"name\", \"value\": \"ucaccept\", \"sessionId\": \"33eaf1f0-ddc5-11e6-b714-317e1de5b0e8\"}","url":"/element","urlParsed":{"anchor":"","query":"","file":"element","directory":"/","path":"/element","relative":"/element","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/element","queryKey":{},"chunks":["element"]},"urlOriginal":"/session/33eaf1f0-ddc5-11e6-b714-317e1de5b0e8/element"}}
Screenshot: available via screen`

This is my implementation:

`#Onedrive Access
redirect_uri = 'http://localhost'
client_secret = 'some_Secret'
client_id_str = 'some_id'
api_base_url = 'https://api.onedrive.com/v1.0/'
scopes = ['wl.signin', 'wl.offline_access', 'onedrive.readwrite']

user_name = 'user@gmail.com'
password = 'somepass'

client = onedrivesdk.get_default_client(client_id=client_id_str,
                                        scopes=scopes)

auth_url = client.auth_provider.get_auth_url(redirect_uri)

def getAuthCodeSelenium():

    phantomjs_path = r'C:\Python36\selenium\bin\phantomjs.exe'
    driver = webdriver.PhantomJS()  # 'phantomjs')

    # driver = webdriver.Firefox()
    # driver = webdriver.Chrome()
    # driver.set_window_size(1, 1)
    driver.get(auth_url)
    driver.implicitly_wait(15)
    login_field = driver.find_element_by_name("loginfmt")
    password_field = driver.find_element_by_name("passwd")
    sign_btn = driver.find_element_by_id("idSIButton9")

    # Fill user name and password
    login_field.send_keys(user_name)
    password_field.send_keys(password)
    sign_btn.click()
    element = driver.find_element_by_name('ucaccept')
    element.click()

    # parse URL to get code and close the browser
    tokens = driver.current_url.split('=')
    driver.quit()

    # access allow to execute all onedrive API's
    access_code = tokens[1].split('&')[0]
    print("access code is here ", access_code)
    return access_code`

1. It used to work.
2. It seems to be a configuration problem.
3. I CAN login using the standard helper class GetAuthCodeServer method.

Any ideas?

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
