### ISSUE TITLE
version_bridge.fragment_upload.fragment_upload_async returns UploadSession when success

### ISSUE THREAD

**Issue by xybu** [OneDrive/onedrive-sdk-python#93]
After the last chunk of file is uploaded to server, `fragment_upload_async()` returns a UploadSession whose _prop_dict is one for `Item` resource. This happens because `ItemUploadFragment.post()` always uses the response to construct `UploadSession` object. Shouldn't it return an `Item` directly if the session succeeds?

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
