### ISSUE TITLE
Is the API for creating a subscription implemented?

### ISSUE THREAD

**Issue by xybu** [OneDrive/onedrive-sdk-python#94]
I saw how to list and update existing subscriptions from the API code, but haven't found a method to create a new subscription (https://dev.onedrive.com/webhooks/create-subscription.htm). Is this API implemented? If so, can I get an example that demonstrates how to use it?

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
