### ISSUE TITLE
Invalid_grant when using onedrive python sdk code flow oathuv2

### ISSUE THREAD

**Issue by app5000** [OneDrive/onedrive-sdk-python#97]
I am using the following code to get an access_token:

    import onedrivesdk

    redirect_uri = 'http://localhost:5000/onedriveauth' 
    client_secret = ’secret’   #secret is the string I got from onedrive app registration
    client_id= ‘id’   #id is the string I got from onedrive app registration
    api_base_url='https://api.onedrive.com/v1.0/'
    scopes=['wl.signin', 'wl.offline_access', 'onedrive.readwrite']

    http_provider = onedrivesdk.HttpProvider()
    auth_provider = onedrivesdk.AuthProvider(
        http_provider=http_provider,
        client_id=client_id,
        scopes=scopes)

    client = onedrivesdk.OneDriveClient(api_base_url, auth_provider, http_provider)
    auth_url = client.auth_provider.get_auth_url(redirect_uri)

    print('Paste this URL into your browser, approve the app\'s access.')
    print('Copy everything in the address bar after "code=", and paste it below.')
    print(auth_url)
    code = raw_input('Paste code here: ')

    access_token=client.auth_provider.authenticate(code, redirect_uri, client_secret) 

But I keep getting invalid_grant error on line:     access_token=client.auth_provider.authenticate(code, redirect_uri, client_secret) 

I don't know what is going on in the background and thus can not debug it.  Can anyone help?  Thanks.

Here is the error msg:

ERROR in app: Exception on /onedriveauth/ [POST]
Traceback (most recent call last):
  File "/Users/Applications/User/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Applications/User/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Applications/User/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Applications/User/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Applications/User/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/Documents/flaskr/myapplication.py", line 69, in decorated_function
    return f(*args, **kwargs)
  File "/Users/Documents/flaskr/myapplication.py", line 3791, in onedriveauth
    access_token=client.auth_provider.authenticate(code, redirect_uri, client_secret)#added grant_type='authorization_code'
  File "/Users/Applications/User/lib/python2.7/site-packages/onedrivesdk/auth_provider.py", line 203, in authenticate
    data=params)
  File "/Users/Applications/User/lib/python2.7/site-packages/onedrivesdk/http_provider.py", line 71, in send
    custom_response = HttpResponse(response.status_code, response.headers, response.text)
  File "/Users/Applications/User/lib/python2.7/site-packages/onedrivesdk/http_response.py", line 61, in __init__
    raise Exception(str(message["error"]))
Exception: invalid_grant

**Comment by patrislav1** [comment]
I have the same issue.

**Comment by rushid93** [comment]
I also have the same issue.

**Comment by hanahana1618** [comment]
Try specifying the same redirect_uri in the app registration as in the code. In my case, I used http://localhost:8080/ 
![screenshot-2018-2-24 test-onedrive registration](https://user-images.githubusercontent.com/13605753/36635304-6d9dd078-1980-11e8-9f61-11a25e96938f.png)

**Comment by app5000** [comment]
Thanks. I found a typo, after that it was fixed.
    On Saturday, February 24, 2018, 4:33:27 PM EST, Ivette Castro <notifications@github.com> wrote:  
 
 
Try specifying the same redirect_uri in the app registration as in the code. In my case, I used http://localhost:8080/

**Comment by tigercosmos** [comment]
I have this error since I call authenticate twice, and the code is only valid for once.

**Comment by app5000** [comment]
Hi,  If I remember correctly, I had a wrong reference somewhere from making a lot of changes.  It is fixed now.  Thanks for sharing.

    On ‎Thursday‎, ‎July‎ ‎12‎, ‎2018‎ ‎05‎:‎09‎:‎07‎ ‎AM, Liu, An-Chi <notifications@github.com> wrote:  
 
 
I have this error since I call authenticate twice, and the code is only valid for once.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
