### ISSUE TITLE
getting invalid_grant with onedrive python sdk code flow authentication

### ISSUE THREAD

**Issue by app5000** [OneDrive/onedrive-sdk-python#98]
I am using the following codes to do authentication for my onedrive app:

import onedrivesdk

redirect_uri = 'http://localhost:5000/onedriveauth'
client_secret = 'my_client_secret'
client_id='my_client_id'
api_base_url='https://api.onedrive.com/v1.0/'
scopes=['wl.signin', 'wl.offline_access', 'onedrive.readwrite']

http_provider = onedrivesdk.HttpProvider()
auth_provider = onedrivesdk.AuthProvider(
    http_provider=http_provider,
    client_id=client_id,
    scopes=scopes)

client = onedrivesdk.OneDriveClient(api_base_url, auth_provider, http_provider)
auth_url = client.auth_provider.get_auth_url(redirect_uri)
# Ask for the code
print('Paste this URL into your browser, approve the app\'s access.')
print('Copy everything in the address bar after "code=", and paste it below.')
print(auth_url)
code = raw_input('Paste code here: ')

access_token=client.auth_provider.authenticate(code, redirect_uri, client_secret)

But I keep getting invalid grant error.  Can someone explain what I am doing wrong?  Thanks.

**Comment by hanahana1618** [comment]
I had a similar error, and I solved it using including the redirect_uri in the app registration.
![screenshot-2018-2-24 test-onedrive registration](https://user-images.githubusercontent.com/13605753/36635238-b737c56e-197f-11e8-98fa-fab3ee269077.png)

**Comment by Anmar-Salih** [comment]
I got the same issue. Thank you hanahana1618, your solution worked like a charm.

**Comment by iamrajeshchauhan** [comment]
Hi @hanahana1618 , I have tried to add the localhost URL in the Microsoft application. But somehow it didn't open the authentication page. It gives me the proxy error in the Chrome browser.

Any idea what would be an issue ?

After changing localhost URL in the code, I'm getting below error.
![error](https://user-images.githubusercontent.com/25196995/46242200-5b351c80-c3e3-11e8-9344-856903a96605.JPG)

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
